apiVersion: v1
kind: ConfigMap
metadata:
  namespace: wireguard
  name: haproxy-config
data:
  haproxy.cfg: |
    global
      chroot      /var/lib/haproxy
      pidfile     /var/run/haproxy.pid
      maxconn     4000
      user        haproxy
      group       haproxy
      daemon
      
      # turn on stats unix socket
      stats socket /var/lib/haproxy/stats
    
    defaults
      mode                    tcp
      log                     global
      option                  httplog
      option                  dontlognull
      option http-server-close
      option forwardfor       except 127.0.0.0/8
      option                  redispatch
      retries                 3
      timeout http-request    10s
      timeout queue           1m
      timeout connect         10s
      timeout client          1m
      timeout server          1m
      timeout http-keep-alive 10s
      timeout check           10s
      maxconn                 3000
    
    frontend minecraft
      bind 0.0.0.0:25565
      mode tcp
      default_backend vanilla_minecraft
       
    frontend mc_tob
      bind 0.0.0.0:25566
      mode tcp
      default_backend mc_tob_server
      
    frontend mc_tob_sftp
      bind 0.0.0.0:2222
      mode tcp
      default_backend mc_tob_sftp
    
    backend vanilla_minecraft
      mode tcp
      server mc-vanilla mc-vanilla-svc.mc-vanilla.svc.cluster.local.:25565

    backend mc_tob_server
      mode tcp
      server mc-tob-server mc-tob-svc.mc-tob.svc.cluster.local.:25565
    
    backend mc_tob_sftp  
      mode tcp
      server mc-tob-sftp mc-tob-sftp-svc.mc-tob.svc.cluster.local.:22
