---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: misskey
#data:
#  POSTGRES_PASSWORD: "test"
#type: Opaque
stringData:
  POSTGRES_USER: "misskey"
  POSTGRES_DB: "misskey"
  POSTGRES_PASSWORD: "test"
---
apiVersion: v1
kind: Service
metadata:
  name: db-svc
  namespace: misskey
spec:
  selector:
    app: misskey-db
  ports:
    - name: http
      port: 5432
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-misskey-db
  namespace: misskey
spec:
  storageClassName: misskey-db
  capacity:
    storage: 16Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - soft
    - rw
    - nfsvers=4
  nfs:
    server: 192.168.1.10
    path: "/k8s/misskey/db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-misskey-db
  namespace: misskey
spec:
  storageClassName: misskey-db
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: misskey-db
  namespace: misskey
  labels:
    app: misskey-db
spec:
  restartPolicy: Always
  containers:
    - name: psql
      image: postgres:latest
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-volume
      envFrom:
        - secretRef:
            name: postgres-secret
      resources:
        limits:
          memory: "1Gi"
          cpu: "1"
      ports:
        - containerPort: 5432
  volumes:
    - name: db-volume
      persistentVolumeClaim:
        claimName: pvc-misskey-db