---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: misskey
spec:
  selector:
    app: redis
  ports:
  - name: http
    port: 6379
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-misskey-redis
  namespace: misskey
spec:
  storageClassName: misskey-redis
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.10
    path: "/k8s/misskey/redis"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-misskey-redis
  namespace: misskey
spec:
  storageClassName: misskey-redis
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: misskey
  labels:
    app: redis
spec:
  restartPolicy: Always
  containers:
    - name: redis
      image: redis:latest
      volumeMounts:
        - mountPath: /data
          name: redis-volume
      resources:
        limits:
          memory: "256Mi"
          cpu: "250m"
      ports:
        - containerPort: 6379
  volumes:
    - name: redis-volume
      persistentVolumeClaim:
        claimName: pvc-misskey-redis
