apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-ngx-config
  namespace: paperless-ngx
data:
  PAPERLESS_REDIS: "redis://redis.paperless-ngx.svc.cluster.local.:6379"
  PAPERLESS_CONSUMPTION_DIR: "/data/consume"
  PAPERLESS_DATA_DIR: "/data/paperless"
  PAPERLESS_MEDIA_ROOT: "/data/media"
  PAPERLESS_DBHOST: "paperless-ngx-rw.cnpg-system.svc.cluster.local."
  PAPERLESS_DBNAME: "paperless-ngx"
  PAPERLESS_URL: "https://paperless.bqc0n.com"
  PAPERLESS_ADMIN_USER: "root"