apiVersion: v1
kind: LimitRange
metadata:
  name: paperless-resource-limits
  namespace: paperless
spec:
  limits:
    - type: Container
      default:
        memory: 512Mi
      defaultRequest:
        memory: 256Mi
