# TODO Use SSHPiper
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wireguard-privatekey-sftp
  namespace: mc-tob
spec:
  encryptedData:
    privatekey: AgCuhNfG8qXJyc8T8L7KrrYENMd7YWAHEWq+SV0Tf7VLtcSh+VxzYcIGIqSv4Y6/IN7Cg3/69NApxInM2PKPVcYZz7x5gFctYkSrvFFLnO8QETpgn6Cb+ezK0PYETGugHpA8xWgI24DSigKRb33IrnjaGd59DJa+xPjTPuyCVjA7uzoOQkakcshHqSYf+2QCkHKzlwo16/VRtwd0YdEUmnhodamX0OwuO84cRtXLNiraFOA0zlSP9u9qIv7vJ/wT24cbTbGT0dEKjTVluDtBuCKPoOVSbUWAjaaBeNmfkwFgfvAMjQn3B4M8om/O/6eLhdlKHwZFYzDLEcmfuXyDro0+XO9t488JUSG+0bx+M29sH8syic7ftPF03QHWNuEWDnS1BOKrpl8T9MxFXxQt8DOHcHBoknCmGqT+BiB70+ioRdyL6pq5ygySFeHngywv4jqsrifeWuJz6IvpiLjI5IqtcqF7s7bTRB1kWpSFnpmblEjxIVgS9uyzmKpKPhwlvOF4s0jj/lPwsk9IxC2jrIi3Fzp53MzNDajI9Sci29XBuPwn0c5tod3rJ3Xv/pNFtrEp1VuQEKUvw57aG5kYg6+bVivmxlHM1Bzyoxbsc3vh190LLdv3iA4RI6eJBpHghWPmYPok5GxgXefDc+g5uCzkz88Y5mAezEdLSpEgwvbp4I7IqWrEx2DIk8Ie6v8Nb/kqAeO52h6zWGnhE7lWwmFKgMzaW7rA1rATCxcudEUcpO9GwuHc5UdmI1p18A==
  template:
    metadata:
      name: wireguard-privatekey-sftp
      namespace: mc-tob
    type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mc-tob-sftp-pubkey
  namespace: mc-tob
data:
  key.pub: |
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIChEEaY7O2dX+vxT90f5JHV92H/uZu3uynJtTCcnau3L
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE65lCWo/lvkIpk2NEnXuOdmruKsPOZyzgndg7y/0Kgr
---
apiVersion: v1
kind: Service
metadata:
  name: mc-tob-sftp-svc
  namespace: mc-tob
spec:
  selector:
    app: mc-tob-sftp
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-tob-sftp
  namespace: mc-tob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc-tob-sftp
  template:
    metadata:
      labels:
        app: mc-tob-sftp
    spec:
      containers:
      - name: mc-tob-sftp
        image: atmoz/sftp:alpine
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        command: ["/bin/sh", "-c"]
        args:
          - |
            apk update
            apk add wireguard-tools
            ip link add dev wg0 type wireguard
            ip address add dev wg0 $WIREGUARD_IP
            wg set wg0 private-key /wg-key/privatekey peer Rybuqf4c2TJt8X/ns/b8ApGgnu9pAtD9zArmlrIf2Hk= allowed-ips 10.9.9.1/32 endpoint minecraft.bqc0n.com:51820 persistent-keepalive 25
            ip link set up dev wg0
            /entrypoint
        ports:
          - containerPort: 22
        env:
          - name: SFTP_USERS
            value: "sftp::1000:1000"
          - name: WIREGUARD_IP
            value: "10.9.9.222/24"
        volumeMounts:
          - mountPath: /home/sftp/production
            name: mc-tob-sftp-production
          - mountPath: /home/sftp/building
            name: mc-tob-sftp-building
          - mountPath: /home/sftp/.ssh/keys/
            name: mc-tob-sftp-pubkey
          - mountPath: /wg-key
            name: wireguard-privatekey-sftp
      volumes:
        - name: mc-tob-sftp-production
          persistentVolumeClaim:
            claimName: mc-tob-data
        - name: mc-tob-sftp-building
          persistentVolumeClaim:
            claimName: mc-tob-data-building
        - name: mc-tob-sftp-pubkey
          configMap:
            name: mc-tob-sftp-pubkey
        - name: wireguard-privatekey-sftp
          secret:
            secretName: wireguard-privatekey-sftp
---