---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wireguard-privatekey-build
  namespace: mc-tob
spec:
  encryptedData:
    privatekey: AgCBjlbj2HWNNVWp2HtytJL44Pp1q+5xgMt46zRexf9ssz66EU8D7D9xQJFllGWj1kj5ds14+5MoifDVMWsrfksnz8DUB8bsefMXEg6e37jl0OTyze8CbSeb5YkZpOZcC0ysiP8zbFU7tCp2h1blsFjms2iaGA1mjkn9/u8v7ZrtHgQ47mtu1YI0izDXTUMd4b/RSLGE+ACie3XTYLa+7E/00Zdw0OKZ1yhEEt6bDQ68lldVJ1/7KcvUUqP1T86SrbSf5eb5qy8mJ2Ot8kJKuIpjkc/IpHpDzXZGZd5LACeffdrxw/w6zbkTsIuPDyrFdI3RypIL0OQGTSAO1xwBLEiY1LPkxx1Fbtf+RhxltHCr4yPQjAE/irlh37+YJUDm3i5s07X5szDdL4jzApFR+UhDhfKzjysA8oVhUUp35s7LT8hiotU/RbpRbylt0/3mrgg8JkINPvdNusGGarZcMM+C3nATP4tk4ZKmex6KkVTSxHDoejBEzvLRZuqrNdd2CBrupQSz4+o7A4BL0b5rIPWyMHJmXD43K0p5ttSX1KsklcPn9WFaB78M4KQO+apyo3eDJzSEfhSMPFIJDQF17vCQ9ffWxbWaIsd5QrfcjIi98shfAtYsk8gi2Mkl2dpJYWjYXyGYuk0ac+XY7aBoqiLi7AdQyrsJRPpawJDu9Z1/RfP7dFtGUKUQqkeTEMWx4pB2uuXM646Iai8pnoymIKd03tpJxBH9QuiW0GS7+NdN9OBEqvavobzgn6E5YA==
  template:
    metadata:
      name: wireguard-privatekey-build
      namespace: mc-tob
    type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  namespace: mc-tob
  name: mc-tob-building-svc
  annotations:
    "lbipam.cilium.io/ips": "10.214.1.2"
    "lbipam.cilium.io/sharing-key": "mc-tob"
spec:
  type: LoadBalancer
  selector:
      app: mc-tob-building-server
  ports:
    - protocol: TCP
      port: 27137
      targetPort: 25565
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-tob-data-building
  namespace: mc-tob
spec:
  storageClassName: nfs-ceph
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: mc-tob
  name: mc-tob-building-server
spec:
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: mc-tob-building-server
  serviceName: mc-tob-building-server
  replicas: 1
  template:
    metadata:
      labels:
        app: mc-tob-building-server
    spec:
      containers:
      - name: mc-tob-building-server
        image: itzg/minecraft-server:2025.4.0-java8-graalvm-ce
        resources:
          requests:
            memory: "2Gi"
        volumeMounts:
          - mountPath: /data
            name: mc-tob-data-building
          - mountPath: /wg-key
            name: wireguard-privatekey-build
        ports:
        - containerPort: 25565
        envFrom:
          - configMapRef:
              name: mc-tob-build-config
      volumes:
        - name: mc-tob-data-building
          persistentVolumeClaim:
            claimName: mc-tob-data-building
        - name: wireguard-privatekey-build
          secret:
            secretName: wireguard-privatekey-build
---
