---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wireguard-privatekey-build
  namespace: mc-tob
spec:
  encryptedData:
    privatekey: AgAJzxLUaQ6oE9pt8oPFpNVOF0z73liLOl1A4Q5PRiPlMF5FsM3gYvr34dFpznS0VaZQ/Id41ISWAH2fZ+EPRwE0RsCRpbx84gY6uVCdbKhnK/KI43qF/AlCXg/PkKQr8KaPhCNoK/1+p4jCW3Lh8MTruwiF9uDJId1v+eLUQnm7av/RHgnT0KNbx3Y4/bWMWv2IWzUEKw/SsJ/EnaekW/OBlVgbFavtPzqjB0j7bDOA93NRmmz4HBgumEezsDk15/lrwLWXTJHBQxhBhHvPX/IajMBrUVI2xd+PTiR3rnEn/eyyjB7gcS1eXsTIoI4lFQcC+AbHZF9yH+i5VmJYlFlktPku+UmM0IRREOh8Zbtn591TQNO5YT2Bc5HCrip1hs4vduS/fIPP+aUpzWn3NOsPrV/dTZnNKPtCZ+SidOvSmirz+fNd4hID04t4nN9Vpl5fFxMqUJ0SYC0/BokCmpUEMX6K6bYaOWZPmk9hRYXHzy3IwbPZvAPSgcC4NC/V9Y6v9pvUFady2TA/FTAuNfUtvCyCKK582QMTz7+iFXk8O4PX5aitS+qjv3cGhvnyM4/tAWrjqN9qsEcwAYfBlfzJAdq10uTaTytcOGtSYSO6vgfZkojITEge/ZCAxz0/ekwYwpsTyF7ZcP6GjnU5Zf4jQD7JMnIP1h3oqweemtlQC5luk69q99neLWGCtlYjpD73uhO47PCEBqY6OZpWi+HQCEXHlD12+Nh6DCyCp2+ffCDg/feL5jNguuky5w==
  template:
    metadata:
      name: wireguard-privatekey-build
      namespace: mc-tob
    type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  namespace: mc-tob
  name: mc-tob-building-svc
spec:
  selector:
      app: mc-tob-building-server
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-tob-data-building
  namespace: mc-tob
spec:
  storageClassName: nfs-ssd-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: mc-tob
  name: mc-tob-building-server
spec:
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: mc-tob-building-server
  serviceName: mc-tob-building-server
  replicas: 1
  template:
    metadata:
      labels:
        app: mc-tob-building-server
    spec:
      containers:
      - name: mc-tob-building-server
        image: itzg/minecraft-server:java8-graalvm-ce
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        command: ["/bin/sh", "-c"]
        args:
          - |
            dnf install -y iproute wireguard-tools
            ip link add dev wg0 type wireguard
            ip address add dev wg0 $WIREGUARD_IP
            wg set wg0 private-key /wg-key/privatekey peer Rybuqf4c2TJt8X/ns/b8ApGgnu9pAtD9zArmlrIf2Hk= allowed-ips 10.9.9.1/32 endpoint minecraft.bqc0n.com:51820 persistent-keepalive 25
            ip link set up dev wg0
            /start
        resources:
          requests:
            memory: "4Gi"
        volumeMounts:
          - mountPath: /data
            name: mc-tob-data-building
          - mountPath: /wg-key
            name: wireguard-privatekey-build
        ports:
        - containerPort: 25565
        envFrom:
          - configMapRef:
              name: mc-tob-build-config
      volumes:
        - name: mc-tob-data-building
          persistentVolumeClaim:
            claimName: mc-tob-data-building
        - name: wireguard-privatekey-build
          secret:
            secretName: wireguard-privatekey-build
---
