# TODO Use SSHPiper
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wireguard-privatekey-sftp
  namespace: mc-tob
spec:
  encryptedData:
    privatekey: AgAcD1M/u8O/y8AX4NNjaHQBsbvK4K/W8UaVtWtOcLOQOqIO/eS5z5dln2U6spa4GOaV7J+obR32ptpMMQHZ6CYY+fpgZi823TRM6fOwVwLmlYPjfz1nA5VGnmPjYNIIWDO+Gkjl5BPMqlqjhfRuQfnmHlvRNx9oz4X3BDujG9rdAaI8K8zUpZDNqTb6J9/t+OLwoTF0iiru89bkNynH394Jz9ZAMy1BwYVP3rpcnm2W0UzMFfOu/0X2SaItKL2ArY9vx/tuTkAlQmN9g4Q9S5jeBvJPtRKrhGNLyPK30HKo8RSx/Cfb/70cSacAFKTintEeXvUSSZb+Xkw3YIy5VE8jWMd+/Naxk+RGK8O5P3wmts8DZO2+wPZ9n+nm/st/xZ/6W3jQw70r6c2KGUlOVKNlsBzpJEmTvqu4wotPoKhNXYEzdma7zgww8kBJETIn+DzaLN9Es6b9Gi72xLxGtaRDdDVR7hLuvnl8Dwl0A05HR/96dKyLezs06SrBnXBWnklkAIgmtRboz2ZyRaZWl6tyQtl3mC8Swq6VY3w24ZcXkthXCB9aFdhnMM0PrvO85GfSfUcR2OFrxURfUph/gFAQlkT2ckONrR31W5bbzTDvMCBoI9+UyFm68wSIDWzF6APN1U1JpD06+zF7EnBClZ49deffnExzTCcZvszM+Tl/ArM5tQ+nChK86t6Gv1yVaDVmJlfXbwFyCRRbr+XgBS26MKU8kuOa1fJ+oagUdd1yzOT6F2j+Ca0MpeAf1Q==
  template:
    metadata:
      name: wireguard-privatekey-sftp
      namespace: mc-tob
    type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mc-tob-sftp-pubkey
  namespace: mc-tob
data:
  key.pub: |
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIChEEaY7O2dX+vxT90f5JHV92H/uZu3uynJtTCcnau3L
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE65lCWo/lvkIpk2NEnXuOdmruKsPOZyzgndg7y/0Kgr
---
apiVersion: v1
kind: Service
metadata:
  name: mc-tob-sftp
  namespace: mc-tob
  annotations:
    "lbipam.cilium.io/ips": "10.214.1.2"
    "lbipam.cilium.io/sharing-key": "mc-tob"
spec:
  type: LoadBalancer
  ports:
    - port: 12303
      targetPort: 22
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-tob-sftp
  namespace: mc-tob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc-tob-sftp
  template:
    metadata:
      labels:
        app: mc-tob-sftp
    spec:
      containers:
      - name: mc-tob-sftp
        image: atmoz/sftp:alpine
        imagePullPolicy: Always
        ports:
          - containerPort: 22
        env:
          - name: SFTP_USERS
            value: "sftp::1000:1000"
        volumeMounts:
          - mountPath: /home/sftp/production
            name: mc-tob-sftp-production
          - mountPath: /home/sftp/building
            name: mc-tob-sftp-building
          - mountPath: /home/sftp/.ssh/keys/
            name: mc-tob-sftp-pubkey
          - mountPath: /wg-key
            name: wireguard-privatekey-sftp
      volumes:
        - name: mc-tob-sftp-production
          persistentVolumeClaim:
            claimName: mc-tob-data
        - name: mc-tob-sftp-building
          persistentVolumeClaim:
            claimName: mc-tob-data-building
        - name: mc-tob-sftp-pubkey
          configMap:
            name: mc-tob-sftp-pubkey
        - name: wireguard-privatekey-sftp
          secret:
            secretName: wireguard-privatekey-sftp
---