---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wireguard-privatekey
  namespace: mc-tob
spec:
  encryptedData:
    privatekey: AgAphVj0xPbwyRSmVPXr1zrLkajSDwKmH05iMfcbaRJmlWGz3XC3pp1p8veCBJapvyXdStlpmUJcehIdrNm1te0Q+TN5+AqfxbJEtgGXFliXfICuQy4MID4eevJ8RSG3zjPT/7hR3HFUe1Nh6AFyk2sW3OnEKBvqy7AXswuCW5JZzx/ZhSFg6gKpmYqVeLd2YGUjsin8SwO3XwZHcN2BzrANxnXUozOAt9bUEYVr0/PK6y4QtWkQgTSU57GKOzPRd51cOkeoMawFhdNEP02ks2JcVLrvajeb8HaeQ4HI3hF34PfGsmttJdpyt++UYK7VA7i444NKcuP94BhFs9UxaSN6qUK+dDbpXuI68er4upTHaB3jkKsYTGgM6WjrjXvx3b9wCkVTlVT6iAQtP/4BzgLb2RPRD+POQiWNA/nRxn9sKN4zoz4bLoHyfgFDarYHeVtk/Cnw2NiP8wL1lDpyJ+63gZ2dyQdlKzXUbuzcsfNvHfiYntrGdhi7/pHkyGIahcHuf+g6QvX5YHlKvldKKeCXXBlEWp6dLAciaowaSp/ow0KoiYqFkfOshDJkDocZmE1b9O3C0SdS3bkiN8KRQUJQy1onoIPiUwiAmf5NnyepKgnmbpSDOczX/VT6ciSzN638IPYG7mXXAXztK9Q4DT9U0oXcZIXL7f+ahGbFT2rEhz7oMQZD5qppqP5EiKuu+8FdG+amIKp2x66taM+pP8MlNGvHXgrtCMdRqJpZlrUG8PfQPOU2avFhBmEhNQ==
  template:
    metadata:
      name: wireguard-privatekey
      namespace: mc-tob
    type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  namespace: mc-tob
  name: mc-tob-svc
  annotations:
    "lbipam.cilium.io/ips": "10.214.1.1"
    "lbipam.cilium.io/sharing-key": "minecraft"
spec:
  type: LoadBalancer
  selector:
      app: mc-tob-server
  ports:
    - protocol: TCP
      port: 27136
      targetPort: 25565
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-tob-data
  namespace: mc-tob
spec:
  storageClassName: nfs-ceph
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: mc-tob
  name: mc-tob-server
spec:
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: mc-tob-server
  serviceName: mc-tob-server
  replicas: 1
  template:
    metadata:
      labels:
        app: mc-tob-server
    spec:
      containers:
      - name: mc-tob-server
        image: itzg/minecraft-server:2025.4.0-java8-graalvm-ce
        resources:
          requests:
            memory: "2Gi"
        volumeMounts:
          - mountPath: /data
            name: mc-tob-data
          - mountPath: /wg-key
            name: wireguard-privatekey
        ports:
        - containerPort: 25565
        envFrom:
          - configMapRef:
              name: mc-tob-config
      volumes:
        - name: mc-tob-data
          persistentVolumeClaim:
            claimName: mc-tob-data
        - name: wireguard-privatekey
          secret:
            secretName: wireguard-privatekey
