---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wireguard-privatekey-build
  namespace: mc-tob
spec:
  encryptedData:
    privatekey: AgA+1D2WwSFKo0ZigJFNYpILmPFY7rrXfD/7ZQ6B7ZZzB+lilYUHk2HwHNAKgow1C7yf7GdAgqMwjM1hm3z5l2FdmZ9NNf5fF651N6d8HPj1Vat8rpMBb4tFqawXix6bJ7mMsHpeeyOoHOuN6rPUWa2c7/fjr1GNpyipayUvgeuCpRZrYwKo3zezeKO+yyfO7xSSto42aWPXmBY+BKykgMxIEIp07ALQjfPwL/P5uY0GyqUqSM9e5bePvSOrN6RytNFUKJnqm7QhciA6uElvowFoKtUlHL0YUapaFBsNzgyp7PPa2gXAaO1r2xrh4ne0us3J/VM80/r5PIHJgG7lLXUIOJ9JJc2/pHNzdR91R/X+RREWasBHf3bAYBjHdiB574UC2ClHCDSqKgupfmPzLdemDzAPk6EOCYA2K+/TrucaSvVp6DWXapg4OzyzlSsuBVRSU4H1Q66fYG0IpMYL8ClPBiAm3WRpjN5K9Lskv9/tW7MKpf0YA2C0hR53YJyH1Wzoqifi3cML5rRSt1YpbFcKwWIYjXprU5T87zn+Hl3iGI9Im/uSFy7WgNLqp7zqVXTVYX0WnM8j9zhYqkte+tfu7k4q9PU8Y0g+fa29KhIAcHkpZPrbZEi0O9NXCJbu1pj0pAqvu2SZutuV6xeNvCGR8RYCdsB1+o2VXRIdLByHqEq19MuKQceveQZcvPwGgMtqs+WV02RJnMQ71c2ie42cD+xDZBbTKk2EUgsuMW15Z+NZZES6fHap5L9vTw==
  template:
    metadata:
      name: wireguard-privatekey-build
      namespace: mc-tob
    type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  namespace: mc-tob
  name: mc-tob-building-svc
spec:
  selector:
      app: mc-tob-building-server
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-tob-data-building
  namespace: mc-tob
spec:
  storageClassName: nfs-ssd-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: mc-tob
  name: mc-tob-building-server
spec:
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: mc-tob-building-server
  serviceName: mc-tob-building-server
  replicas: 1
  template:
    metadata:
      labels:
        app: mc-tob-building-server
    spec:
      containers:
      - name: mc-tob-building-server
        image: itzg/minecraft-server:java8-graalvm-ce
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        command: ["/bin/sh", "-c"]
        args:
          - |
            dnf install -y iproute wireguard-tools
            ip link add dev wg0 type wireguard
            ip address add dev wg0 $WIREGUARD_IP
            wg set wg0 private-key /wg-key/privatekey peer Rybuqf4c2TJt8X/ns/b8ApGgnu9pAtD9zArmlrIf2Hk= allowed-ips 10.9.9.1/32 endpoint minecraft.bqc0n.com:51820 persistent-keepalive 25
            ip link set up dev wg0
            /start
        resources:
          requests:
            memory: "4Gi"
        volumeMounts:
          - mountPath: /data
            name: mc-tob-data-building
          - mountPath: /wg-key
            name: wireguard-privatekey-build
        ports:
        - containerPort: 25565
        envFrom:
          - configMapRef:
              name: mc-tob-build-config
      volumes:
        - name: mc-tob-data-building
          persistentVolumeClaim:
            claimName: mc-tob-data-building
        - name: wireguard-privatekey-build
          secret:
            secretName: wireguard-privatekey-build
---
