---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mc-tob-config
  namespace: mc-tob
data:
  LEVEL_TYPE: "flat"
  GENERATE_STRUCTURES: "false"
  TYPE: "paper"
  EULA: "true"
  LOG_TIMESTAMP: "true"
  MAX_PLAYERS: "10"
  MEMORY: "4G"
  MOTD: "Tower of Babel"
  OPS: "bqc0n,soramame_256,KURAGON,TashiKani_,IchinoseYuki,urabe03,Malb7mm,HeihoDESU,yuu50"
  OVERRIDE_WHITELIST: "true"
  PVP: "false"
  SPAWN_PROTECTION: "0"
  TZ: "Asia/Tokyo"
  USE_AIKAR_FLAGS: "true"
  VERSION: "1.12.2"
  WHITELIST: "bqc0n,soramame_256,KURAGON,TashiKani_,IchinoseYuki,urabe03,Malb7mm,HeihoDESU,yuu50"
  # This is not an itzg/minecraft-server's env var
  WIREGUARD_IP: "10.9.9.11/24"
