---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "bgp-pool"
  namespace: kube-system
spec:
  blocks:
    - cidr: "10.214.1.128/25"
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: bgp-pool-fixed
  namespace: kube-system
spec:
  blocks:
    - cidr: "10.214.1.0/25"
  serviceSelector:
    matchLabels:
      lbipam: fixed

