# TODO Use SSHPiper
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mc-tob-sftp-pubkey
  namespace: minecraft
data:
  key.pub: |
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIChEEaY7O2dX+vxT90f5JHV92H/uZu3uynJtTCcnau3L
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE65lCWo/lvkIpk2NEnXuOdmruKsPOZyzgndg7y/0Kgr
---
apiVersion: v1
kind: Service
metadata:
  name: mc-tob-sftp
  namespace: minecraft
  labels:
    lbipam: fixed
  annotations:
    "lbipam.cilium.io/ips": "10.1.0.1"
    "lbipam.cilium.io/sharing-key": "minecraft"
spec:
  type: LoadBalancer
  selector:
    app: mc-tob-sftp
  ports:
    - port: 12303
      targetPort: 22
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-tob-sftp
  namespace: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc-tob-sftp
  template:
    metadata:
      labels:
        app: mc-tob-sftp
    spec:
      containers:
      - name: mc-tob-sftp
        image: atmoz/sftp:alpine
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "512Mi"
        ports:
          - containerPort: 22
        env:
          - name: SFTP_USERS
            value: "sftp::1000:1000"
        volumeMounts:
          - mountPath: /home/sftp/production
            name: mc-tob-sftp-production
          - mountPath: /home/sftp/building
            name: mc-tob-sftp-building
          - mountPath: /home/sftp/.ssh/keys/
            name: mc-tob-sftp-pubkey
      volumes:
        - name: mc-tob-sftp-production
          persistentVolumeClaim:
            claimName: mc-tob-data
        - name: mc-tob-sftp-building
          persistentVolumeClaim:
            claimName: mc-tob-data-building
        - name: mc-tob-sftp-pubkey
          configMap:
            name: mc-tob-sftp-pubkey
---