---
apiVersion: v1
kind: Service
metadata:
  namespace: minecraft
  name: mc-tob-svc
  labels:
    lbipam: fixed
  annotations:
    "lbipam.cilium.io/ips": "10.1.0.1"
    "lbipam.cilium.io/sharing-key": "minecraft"
spec:
  type: LoadBalancer
  selector:
      app: mc-tob-server
  ports:
    - protocol: TCP
      port: 27136
      targetPort: 25565
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-tob-data
  namespace: minecraft
spec:
  storageClassName: nfs-ceph
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: minecraft
  name: mc-tob-server
spec:
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: mc-tob-server
  serviceName: mc-tob-server
  replicas: 0
  template:
    metadata:
      labels:
        app: mc-tob-server
    spec:
      containers:
      - name: mc-tob-server
        image: itzg/minecraft-server:2025.12.0-java8-graalvm-ce
        resources:
          requests:
            memory: "2Gi"
          limits:
            memory: "5Gi"
        volumeMounts:
          - mountPath: /data
            name: mc-tob-data
        ports:
        - containerPort: 25565
        envFrom:
          - configMapRef:
              name: mc-tob-config
      volumes:
        - name: mc-tob-data
          persistentVolumeClaim:
            claimName: mc-tob-data
