---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: minio-daily
  namespace: pg-clusters
spec:
  retentionPolicy: "7d"
  configuration:
    destinationPath: s3://cnpg-backups/daily
    endpointURL: http://minio.bqc0n.internal:9000
    data:
      compression: bzip2
    s3Credentials:
      accessKeyId:
        name: minio-creds
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: minio-creds
        key: SECRET_ACCESS_KEY
    wal:
      compression: zstd
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds
  namespace: pg-clusters
spec:
  encryptedData:
    ACCESS_KEY_ID: AgBKkd5s9dvjSbZM8IyF7z2mU511Q3MIbUTByKSonja3Z6dVXzZNnTCleQ6wZeqBoY9dVmtWBHzo5VJjB5vIATw6vkW5LeX7xXSxMUw//glfBZZRvSoCnBBZ3DCFkJxLf/rGLU4vbxIsZnkfp4kWdBFEIdT4EN2iJHKQNb4lLGigup1F1Z47uU1Wqzo6A8crEBr3P33UjfibsqgNA4zDNmTTwcT7D+aybW8LvRQOIA81Vt+hI1VpMsF34+CAurGlfty+pWDKDU0Ngigc82RImI/ck8+v8f6CDyppWRIRC6dzSWCrR2KxMocXYBqpTauECFIP9/MmBkGxp/kWdA2KqDZPzbXclGKWcRrQS5j5wNHdhU9fhnIDKPKsFD4r0C1n4HP6xN2szy8AEzZgV7OX+LHDIM/BtDFgF8qjoX1rnixGsoW7otlhv9qzwN6E7wcIGbaGRDkynrobhoCyiAuvBOQCqQduSORFnXjzkPoNqXqUHFTMvvJ6jzsSE6EcTp3pZCfwVIi13lujf5fxT2MvoQR93dGAm1jq+H5ydUxg8yzw+8EtQUI9FnqlfWeYRdXqjPSao5JJrBy2ItTSYI/xfe63XmuSAX+v1IHbXS2Pgt8UKfYZQoPeXdOVQJMUd/2rgQROjVDFeCp4vKaMlYQdP6RQUT98Bfhkc4uyBKtrA8IoF17QhXvwCEzXGpz1NDMR8dNWI90AQQYQVhCf+GDH3nL+ViFo+Q==
    SECRET_ACCESS_KEY: AgCL+qiypdUxGd2RQPm/JQKns1Mgl3zH0onlLfZoNLNjiY5+cXOD6mqwHp2OB597drTpGdahUCDB4GhOy5dxR2SPrbI9ZfPNEhIdYFmXLjwnHiM9ZWXFdnGmPW5REwrJCsX5L7Snnc0d76yLcjj3HOf/t4ZfsnLkyZnLjxlCux+6VPWAUXuxNBqqhyISB+65MwHo/cSj24OWaCjXaNAHikiPfV1vT34gAALtaeSrEVpTHjN771fmjB6SzdtILdk2aE62MnmZj0T0ftVxYGVj/kSJMWxXDzx9EcZqsFWY22/xhJ3IA2+69DO6MAe/Ki/VBBMJxtHDw/H4fUgfN8gTf0Spp9tzszdLPCGqzGoYsyYbgRAtKDrcdfUpnmJ7vMei7CxTgxDBtdGbl3KxCH5IjSYaqv+hbiCjkcu7rtrZj7jXW4/JDx95+lUCHl7pGWHE023UWfMNI2rekaCeMnIvoqas1c2B/TwtD1ou4TL129lm8X3Fd6l8Mfzt8VgGoeeha3Y28P1HQEgMTtDpO7Q/0aVSL4ecv3iwtEDAGylZVpV4GuKwj/v19aNnzY6Md49g9ZefVP56UXKrPw0DqNbGE6J6LpcRwubCKzhSNX1BEmWUgcxyO1Kyi4eYKs1aaqCxq7IaJWMf7ANpJHMHMQR6qbOv1MLtEUYbwhIZa1Yw55sXxhn5t2vEt9QJvLviXv9SKgGgTuoyboWytgPmxsEkdaBLI03DSC1PQ/9Yg5Zmr9kOHWAaOS9oXpRJ
  template:
    metadata:
      name: minio-creds
      namespace: pg-clusters
    type: Opaque
