---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitea
  namespace: cnpg-system
spec:
  instances: 1
  bootstrap:
    recovery:
      source: origin
      owner: app
      database: gitea
      secret:
        name: gitea-db-creds
  storage:
    storageClass: nfs-ceph
    size: 10Gi
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        serverName: gitea
        barmanObjectName: minio
  externalClusters:
    - name: origin
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: minio
          serverName: gitea1
