apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich
  namespace: cnpg-system
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.5-v0.3.0
  bootstrap:
    recovery:
      source: origin
  enableSuperuserAccess: true
  superuserSecret:
    name: immich
  postgresql:
    shared_preload_libraries:
      - "vectors.so"
  storage:
    storageClass: nfs-ceph
    size: 10Gi
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: minio
        serverName: immich
  externalClusters:
    - name: origin
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: minio
          serverName: immich-gen2