---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: datasource-influxdb
  namespace: dash
spec:
  valuesFrom:
    - targetPath: "secureJsonData.token"
      valueFrom:
        secretKeyRef:
          name: "influxdb-auth"
          key: "admin-token"
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    name: Influxdb2
    type: influxdb
    access: proxy
    basicAuth: true
    url: http://influxdb-svc:8086
    isDefault: false
    jsonData:
      version: Flux
      organization: home
      defaultBucket: proxmox
      tlsSkipVerify: true
    secureJsonData:
      token: ${PROMETHEUS_PASSWORD}
