---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: dash
spec:
  storageClassName: nfs-ssd-1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: dash
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - targetPort: 3000
      port: 3000
      nodePort: 30002
      protocol: TCP
      name: http
  externalTrafficPolicy: Local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana-deployment
  namespace: dash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana
          volumeMounts:
            - mountPath: /etc/grafana
              name: grafana-config
            - mountPath: /var/lib/grafana-provisioning
              name: grafana-provisioning
          ports:
            - containerPort: 3000
      volumes:
        - name: grafana-config
          configMap:
            name: grafana-config
        - name: grafana-provisioning
          configMap:
            name: grafana-provisioning
