---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: dash
spec:
  storageClassName: nfs-ceph
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: dash
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - targetPort: 3000
      port: 80
      nodePort: 30002
      protocol: TCP
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana-deployment
  namespace: dash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana
          volumeMounts:
            - mountPath: /etc/grafana
              name: grafana-config
              readOnly: true
            - mountPath: /etc/grafana/provisioning/dashboards
              name: grafana-dashboards
              readOnly: true
            - mountPath: /etc/grafana/provisioning/datasources
              name: grafana-datasources
              readOnly: true
            - mountPath: /var/lib/grafana
              name: grafana-data
          ports:
            - containerPort: 3000
          env:
            - name: INFLUXDB2_ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: influxdb-auth
                  key: admin-token
      volumes:
        - name: grafana-config
          configMap:
            name: grafana-config
        - name: grafana-dashboards
          configMap:
            name: grafana-dashboards
        - name: grafana-datasources
          configMap:
              name: grafana-datasources
        - name: grafana-data
          persistentVolumeClaim:
              claimName: grafana-data