# TODO: Migrate to helm chart
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-data
  namespace: dash
spec:
  storageClassName: nfs-ceph
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
  namespace: dash
spec:
  type: NodePort
  selector:
    app: influxdb
  ports:
    - targetPort: 8086
      port: 8086
      nodePort: 30001
      protocol: TCP
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: influxdb
  name: influxdb-deployment
  namespace: dash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
        labels:
          app: influxdb
    spec:
      containers:
        - name: influxdb
          image: influxdb:2.7.11
          volumeMounts:
            - mountPath: /var/lib/influxdb2
              name: influxdb-data
          ports:
            - containerPort: 8086
          env:
            - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: influxdb-auth
                  key: admin-token
            - name: DOCKER_INFLUXDB_INIT_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: influxdb-auth
                    key: admin-password
          envFrom:
            - configMapRef:
                name: influxdb-config
      volumes:
        - name: influxdb-data
          persistentVolumeClaim:
            claimName: influxdb-data