---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: influxdb-auth
  namespace: dash
spec:
  encryptedData:
    admin-password: AgD5rVHyKVjmCM5w0IPNPX0T1+/MyiEYABHegKefe7IqD8WNO9WVo4MBJ1oDFj2AJtD0qONDedDQnCNQifWAU3L/hE7LwzP0q+faVggcBlQxrTxUXNmukOtZMN/8zPkLcI0+nc3y+gT1Zq+l2+Q7ZAQhPPx/9ok8U/Ov79s0sR8V4jHUWVb0c9fZKqfypclkgXQB+B8M/y0+iOJ7ZQNkm1aizmbtb83ZtCzFs+r+Yw+wn0xGs86qcQFOVIDZBj/lgxtpsAVDo3TJK39/eIblDQ2PFLJnGUHWjUy6K/UI9wrCK5n+qXvRvl43bF2EvqwQb60aRRyi7x0yrMC8h0DlWsmNOeDAZU4rYYAFv8Wh23KDUPYpwaymhHzJlw199CSQgcZQWM9ve92UPsXWvnkcIquBR3N5C8GVt7SkXnG0HkJ/WttJyd9M72DCOxbwaoSBUkfkNQ2ZuEEfgETMzqOZ21XgCWgG/S/Xfk9AeL12GiMhmJgsNsdbQPVs2kMqwD3d3sPA1oIIhmdOEmZ8joNyRbyR35heQiF5mtl3imHAq1ybD8WxlAQuGlwKAQhi5e4+TUeR/aHSb+Ipp2IyICoPe8FYwtTA+yWwG/k4Rs3Vcr6HFS5Y0+WbLKk60SvhUUTAKy2PJtBvmViTUNL2YkCxc2fosRWvUMSy68D6kVmqS8aQqiGiVWoZEfhImTtExtvWkHqEouGWJfBwLIeKN1Hqypy0YaUPjhdKFd0=
    admin-token: AgAjnz97Dy4OcpaVkeiA71633joLDk0FIpp/lAgqKbH50obLvW5sYROqzIpF4tAame+UqYpKIdSIwG+bgp9Bv2+ZrcyJEMzmG6IUuzaUiig/p94/bLknlmPWyv1nGiNlVQroeLYrsr7PHCfFRfvKiqEKxPoiadTkisKSewnqqKT5UO5GxnsW/Tw2woTutbY0bbDn5LvfUvYN9gbJXBOsEx5zMd6EB1Vw3uwNwIoIz4WQIC4o/MSMu0zGoti3DCMA2N3/17TN2QX6fVT/DlpBxP4gDxc5OnG284SPVf70HECbTMbV/6xDHth4GNr58Z1yv/zW9uZiaj2vSTQXoGOVBx3YUdVIME5Yb5NEHymmSIYddrH8pxZ/O/KLGlNz+oUZtbZ/5c03H1tna/l+w/Ql7rx/qliiXbth34a06TTkt9W5ePVuMvuW/Ec4mLTpQ4XRta0j7FzEF6Gv+GguwOULvTARr5jtiUYAb9baUH1tyHbJ7JZxfdwmh8dZEho8rc+WF829KcP8ASk4Enlp/RPtE48BiAxH3rirXq6ArpKislrZAEt5uJTLFyJKGoYH6+gMpO3aNo5ZIecI9E415WJosU64DHLjdXnoF6kP5sJDtw5angq5cfAztBw/xKy8Ryk/5C6IjTyJ+QqM/3SFNRYrsXv1O4gNSp8K39BZRHWaO25J+U37+X2uNDQ357JrT4JxyviKndfzc8tEXYr3QiYxIeRzm0ejebBGfflvvmuRg1Q4EzAV2dxkFtiXE/zf7fjShFB0LYhEpqS2v5CqTG/5cd4tUXuwYeoJhH4KAqK8b3Vdr50pls/k3hBo
  template:
    metadata:
      name: influxdb-auth
      namespace: dash
    type: Opaque
