---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb2-data
  namespace: dash
spec:
  storageClassName: nfs-ssd-1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
---