---
apiVersion: v1
kind: Secret
metadata:
  name: restic-repo-password
  namespace: dash
type: Opaque
stringData:
  PASSWORD: "nopass"
---
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: dash-backup-schedule
  namespace: dash
spec:
  podSecurityContext:
    runAsUser: 0
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  backup:
    schedule: "0 3 * * *" # 3AM
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 2
  prune:
    schedule: "@weekly"
    activeDeadlineSeconds: 7200
    retention:
      keepDaily: 14
      keepMonthly: 12
      keepYearly: 100
  backend:
    rest:
      url: "http://restic-rest.backup.svc.cluster.local./dash/inflxudb-backup"
    repoPasswordSecretRef:
      name: restic-repo-password
      key: PASSWORD
