apiVersion: v1
kind: LimitRange
metadata:
  name: dash-resource-limits
  namespace: dash
spec:
  limits:
    - type: Container
      default:
        memory: 512Mi
      defaultRequest:
        memory: 256Mi
