---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wireguard-privatekey
  namespace: mc-vanilla
spec:
  encryptedData:
    privatekey: AgDm8yPiKfdVizOfFHeAwo3fpdq8UibRZEwozaK3EPfLj+jPwmfprif21BiQqnzsQbPCbqwnaQPohSjQVR5B98QXawNAhxpg+s0YYIlMiJrCrLfTG+4oNixWBztgFRNQHHi5BW+xnUO3yGrlZVawafVFS4Z3G+SVO5tvzKVtXh3Tn+YjQIzfuzxVgUE7pNB1SpfybjqKwLu0aKxhARy+dbegRO83uzim3KJbUhIJo4+WzeFJTTnowISjVTgsaNUZ5OaeEkWnKXb4XOdQ1i/znT4GQYfryi33IDOcu3cbyY90S8e0jzxvp4BNWELIngK1Xk7BvwJgDbOrKc8QEEStSsJlEIx7iBN3BLvwA55q8i3REMw8faCt73XRzPUr9gJrcwT00nmlMuh2WUw8/mbDmV2jrbpVo57RGJYZZHKCoO+IZSUNc4V4c1up6+aXe5wdPlpXE2rRAKKE78yNa0IR9r4AAYn4fQ6BasmP3tJ6GVT06IQvxhOjif4DMQ9Y1DZRQV4sPJLnXKKwemk7CZRwJzzMevWfjsQ314nF1tsOOoy6PCznuWiRQ5I4nYNYqaAOzlD4VKXVg+OHX0sgVP98iWAlEQXt8+6B5pGhP9kG4TQMUYD2hHUJJMkM9FIam9XQR6t81Bd4Vu5dE0c3byBh6FqPaWN2x56pcMAEpUZuLZMz307WitIfp4nwfmfyDqKPpBxkBPZnWSYq5S9quWAK/XOdOg608dm7CB+pDmDgVlrcA2jSIQ5j7FAhrkesqw==
  template:
    metadata:
      name: wireguard-privatekey
      namespace: mc-vanilla
    type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  namespace: mc-vanilla
  name: mc-vanilla-svc
spec:
  selector:
      app: mc-vanilla-server
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-vanilla-data
  namespace: mc-vanilla
spec:
  storageClassName: nfs-ceph
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: mc-vanilla
  name: mc-vanilla-server
spec:
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: mc-vanilla-server
  serviceName: mc-vanilla-server
  replicas: 1
  template:
    metadata:
      labels:
        app: mc-vanilla-server
    spec:
      containers:
      - name: mc-vanilla-server
        image: itzg/minecraft-server:java17-graalvm
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - SYS_MODULE
        command: ["/bin/sh", "-c"]
        args:
          - |
            dnf install -y iproute wireguard-tools
            ip link add dev wg0 type wireguard
            ip address add dev wg0 $WIREGUARD_IP
            wg set wg0 private-key /wg-key/privatekey peer Rybuqf4c2TJt8X/ns/b8ApGgnu9pAtD9zArmlrIf2Hk= allowed-ips 10.9.9.1/32 endpoint minecraft.bqc0n.com:51820 persistent-keepalive 25
            ip link set up dev wg0
            /start
        resources:
          requests:
            memory: "3Gi"
        volumeMounts:
          - mountPath: /data
            name: mc-vanilla-data
          - mountPath: /wg-key
            name: wireguard-privatekey
        ports:
        - containerPort: 25565
        envFrom:
          - configMapRef:
              name: mc-vanilla-config
          - secretRef:
              name: mc-vanilla-whitelist
      volumes:
        - name: mc-vanilla-data
          persistentVolumeClaim:
            claimName: mc-vanilla-data
        - name: wireguard-privatekey
          secret:
            secretName: wireguard-privatekey
