apiVersion: v1
kind: LimitRange
metadata:
  name: seafile-resource-limits
  namespace: seafile
spec:
  limits:
    - type: Container
      default:
        memory: 512Mi
      defaultRequest:
        memory: 256Mi
