---
apiVersion: v1
kind: Service
metadata:
  namespace: seafile
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: seafile
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mariadb
          image: mariadb:11.8.2
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data
          envFrom:
            - secretRef:
                name: seafile-db-secret
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: seafile-db-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: seafile
  name: seafile-db-data
spec:
  storageClassName: nfs-ceph
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi