---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: immich
  name: immich-data
spec:
  storageClassName: nfs-hdd-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi