---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: immich-tls-cert
  namespace: immich
spec:
  secretName: immich-tls-cert
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
  duration: 8760h # 1 year
  privateKey:
    algorithm: RSA
    size: 2048
    rotationPolicy: Never
  renewBefore: 360h # 15 days
  subject:
    organizations:
      - bqc0n
    countries:
      - Japan
  dnsNames:
    - immich.bqc0n.internal
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich-ingress
  namespace: immich
  annotations:
    "lbipam.cilium.io/ips": "10.1.0.100"
spec:
  ingressClassName: cilium
  rules:
    - host: immich.bqc0n.internal
      http:
        paths:
          - backend:
              service:
                name: frontend
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
  - hosts:
    - immich.bqc0n.internal
    secretName: immich-tls-cert