apiVersion: v1
kind: LimitRange
metadata:
  name: immich-resource-limits
  namespace: immich
spec:
  limits:
    - type: Container
      default:
        memory: 512Mi
      defaultRequest:
        memory: 256Mi
