---
- name: Wait for boot
  ansible.builtin.wait_for_connection:
- name: Gather Facts
  ansible.builtin.setup:
- name: Tokyo Timezone
  become: yes
  ansible.builtin.timezone:
    name: Asia/Tokyo
- name: Include sops secrets
  community.sops.load_vars:
    file: "secrets.sops.yml"
    name: sops
    expressions: ignore
- name: apt update
  become: true
  ansible.builtin.apt:
    update_cache: yes

- name: Setup apt-cacher-ng
  ansible.builtin.apt:
    name: apt-cacher-ng
    state: latest

- name: Samba - Create User
  ansible.builtin.user:
    name: bqc0n
    password: "{{ sops.smb_bqc0n_password }}"
    state: present
    shell: /bin/bash

- name: Create Share Directory
  ansible.builtin.file:
    path: "/mnt/shared/bqc0n"
    state: directory
    owner: bqc0n
    mode: 0700

- name: Group
  ansible.builtin.group:
    name: sftpusers
    state: present
- name: Samba Server Role
  ansible.builtin.include_role:
    name: vladgh.samba.server
  vars:
    samba_log: /var/log/samba/samba.log
    samba_log_level: 1
    samba_global_include: global-include.conf
    samba_users:
      - name: bqc0n
        password: "{{ sops.smb_bqc0n_password }}"
    samba_shares:
      - name: bqc0n
        owner: bqc0n
        create_mode: "0700"
        directory_mode: "0700"
        read_only: false
        writable: true
        write_list: +bqc0n
        valid_users: +bqc0n
        browseable: true
        guest_ok: false
        path: "/mnt/shared/bqc0n"