---
apiVersion: v1
kind: Service
metadata:
  name: mc-tsb
  namespace: minecraft
  labels:
    lbipam: fixed
  annotations:
    "lbipam.cilium.io/ips": "10.214.1.1"
    "lbipam.cilium.io/sharing-key": "minecraft"
spec:
  type: LoadBalancer
  selector:
    app: mc-tsb
  ports:
    - port: 27139
      targetPort: 25565
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-tsb-data2
  namespace: minecraft
spec:
  storageClassName: nfs-ceph
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mc-tsb
  namespace: minecraft
spec:
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: mc-tsb
  serviceName: mc-tsb
  template:
    metadata:
      labels:
        app: mc-tsb
    spec:
      containers:
        - name: mc-tsb
          image: itzg/minecraft-server:2025.4.0-java17-graalvm
          resources:
            requests:
              memory: "2G"
            limits:
              memory: "5G"
          volumeMounts:
            - mountPath: /data
              name: mc-tsb-data
          ports:
            - containerPort: 25565
          envFrom:
            - configMapRef:
                name: mc-tsb-config
      volumes:
        - name: mc-tsb-data
          persistentVolumeClaim:
            claimName: mc-tsb-data2
