---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: redmine
  namespace: cnpg-system
spec:
  schedule: "0 4 * * *" # 4 AM every day
  backupOwnerReference: self
  cluster:
    name: redmine