---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: redmine
  namespace: cnpg-system
spec:
  schedule: "0 0 4 * * *" # 4 AM every day. Go cron format.
  backupOwnerReference: self
  cluster:
    name: redmine
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: immich
  namespace: cnpg-system
spec:
  schedule: "0 0 4 * * *" # 4 AM every day. Go cron format.
  backupOwnerReference: self
  cluster:
    name: immich
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: paperless-ngx
  namespace: cnpg-system
spec:
  schedule: "0 0 4 * * *" # 4 AM every day. Go cron format.
  backupOwnerReference: self
  cluster:
    name: paperless-ngx
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: gitea
  namespace: cnpg-system
spec:
  schedule: "0 0 4 * * *" # 4 AM every day. Go cron format.
  backupOwnerReference: self
  cluster:
    name: gitea
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: apps
  namespace: cnpg-system
spec:
  schedule: "0 0 4 * * *" # 4 AM every day. Go cron format.
  backupOwnerReference: self
  cluster:
    name: apps
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: s3-creds
  namespace: cnpg-system
spec:
  encryptedData:
    ACCESS_KEY: AgCIp8U99CAmLXYHpta7krjaZGokbHr+ESjZy4GxCji1/7xNNvT/PLwcMv1Pu5IiURpFKv0VsxZXCTmzJ9cotl4a+vPRJzKwr5vcToja5A7sJAidMv4HNqO3xx6J8VCa7lA9TyTsITJcdlF/1F0yqx7ztu2HkGXouMlgHD8ykGF//lssnItW+A/Sa+dZ1EKqENzf5eeKwRMDQAl79tv0c8p12Ae5ji1JSiI7Tw6H4GNnBik5JvFNtWduGR+nyz61lEYa8fnM3Dis+l3Ke5On756zvc2q66u6EnApFajs6/ROv0gOnLIgpWvlTumiaig4kwD0CNs2JI5z0hWHM1cUeFrfqkj6rQ/dGL+hF4t9Q3lQVQExjrAYLVlpgfptXSs876Y6aqV9Mn3489KutC663XLp1PTyyzE9FhkWzpIx8LLIzVdZqFN7xa4lNU3A97j2o3N1mAkLVc7vXpvFuW5WFHA7z4ArbfPc9WDr3T435P/O8EWBqWl5BN9U4pNZmlhE28MOouwPlkex0ginLkXwByybewrjIwqLugrg2OR9r5FECCeJF/wO09aU+3F1JaB0eVj5z93rZdTHHFXsOjPQbMF7FzNbRz6UezhZTsvQyh4RvoehyApTdxMLI0/3xTK/jD8zPh/rnSVrVks6WEn3nhXGiDAE7xSMoSnOmMQSdxmPGeX1W19m9RIhx97lXjRckJ0GWutY/5h6THXHi0pt9OMGKlPL4Q==
    SECRET_KEY: AgB9PammMkWUgAqnBE7U/y/hIdldF9hvglb4kJXC+m2UfpeXsDxDZOUMMYAqNlzXQtUKFLFV1D4BCvUryan236Ty8r20hGTl+fanTOnuR/7/qhFBwCpgwcWW9rKLX1Frx1PsfRbORodxjeaZ9mGlpGaiLnZJX/LFr2gc1d9MoEGInSYSCLeGfPQlouK7oYc9wFdWLefnCIelGR2BeYk1wW1gms89Hw5t0FDTa1ZXe2i4iOIgoiqBTu7wf/3jD9ny9LATqLJcpJbDJS0c/FAeLbnWPPHPVz2ZDsQIpZ3sCNFMHrjo1QwMEvrkKEF2UntlhlikrCPtabb0/pj48vrbuddXcGAIK+tLNykj2rgYgR7fR9UJATVf9cqndPolrdAD2OyOOP7UNvWe2wid+1BeQlJp2/XppXvjKHaxlVRzvj/WjE1IYSOhl1MVuGcCQKPdSt0yX2ucJ/fGNQtCx/mR2YF3O+qOK2k077Se+dCTqPzFJo0lPRzeE8o+cDHcW5M6hVuf/oA3GMtddM7zaYTk5nOiauRxdm7EYxBQuc98p530CLWTitevrMKzxvuBNxwMehdJmIOTtfWyh22IMdnGjGaJnqMEnNIYYs0BFm/4bRFSqz7KQ0JUbn4eJp3LfIH7JAtuFaIRZZIm38mq9ghJsUCz6OGlp52CqBv3Zn6pANqeSrlGpOkhvpQk/bSMRX7c693QRtUa0ignCp4cJyYyEk2ZF14h9Sahsx6NUc646RXOWSA01gXaCt0X
  template:
    metadata:
      name: s3-creds
      namespace: cnpg-system
    type: Opaque