---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: redmine
  namespace: cnpg-system
spec:
  schedule: "0 0 4 * * *" # 4 AM every day. Go cron format.
  backupOwnerReference: self
  cluster:
    name: redmine
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: s3-creds
  namespace: cnpg-system
spec:
  encryptedData:
    ACCESS_KEY: AgAy81GrUIRBMbGdPMohoHJ+/jiO2jMzPpOJNyhnCUeiV22vV6GP1v8tAs+M1B7Yl5yc/gHfA3dwZEJPx3MsbgJj06xPVKZUHkltmDf4B2H1Ln70JI6iVH2YRY5QvlqNITeb2pyowdgbtVnUs970GklVJk25Mdz6FOd4CYoj33AZ6aZI7B5/2O5ZFEJLKLuVO/3Yp80lY4t2iLf1RxrS+LTLY4V7wLfsDrp9WHfmaCi3Dj7WdNlAbSejaCLBGJo6x6AWHESLx9yQvUMI784uRA6XpZCA/2EExYhiggBDqdCjNLQiHIqF6BE0kF6Bb3aZuv7ycIp4Wc6YNXnX2t75Wfe/xon2h/mTkT9hud/QwxRMSUh6Xo140kD+k84u6CV8PnfEP9AHRhEYdx+zDA2Zx7LMs0Vsdr4Ksf5aLd0NBiItQxtjSqILuO6C2d6H870uo7YnmgOvvPXxJrBT3yzAsMMeu4LfKZdmUbq8On8WjGroZFDhiRT3Co7T7QCkmzdwLl5uK4tmN4UwPm1cdrY3CIMESkiD0/r8UUe2IQDJMMUHOS1XgU2H/Z2jz7UsFSUb+3CCiG+7fkR7V2Zlgwq9dnb4z0SInTVidGqin6TtzUnri8oRQUjDm5d+TRdHmGhVy+t34o5vQGIDYkvcrpm3F7CoG/BpRycwcNeCD9XeffuIjdKY1kDqvYsuXnpCdS9hV0r3hj+FCzC7i6Izy5/FKqU=
    SECRET_KEY: AgA7UiDRSHEwJ2UOsZRyJ/GgretfD+eEbLjsIKpxjNLRHJrw5OFLQJUKM06FbG7qrUHU3+Y5kcQ9eFA9yR5xilRF+DF6UbSu7OG/IUhq9QfL325NPkH78HZ24hk7hlD1A1d3QeT8Zl9FisxO00jtLpjh+S32UdTn23GAhl4JaRhtGujvAVooRejkczcj5YdnVLEGO6Ura1O9y9c0V1W6CLLk2tZ8IkMI3hgkn1PdDjY+WN7AeLoLoyHlz0eAfce1dam6pcs1V2MZ/ObixQksAKJZLC1mGwJCjxNF52Kz5qvXgkBoaLC/ELr2oI6b0WPN7mv5HnAUrCwAAfmVfnJ3t1svpjjUo6qERfMmGtE7KVN8IjIFA/c3p+l1JWQLxF+g/7W06Ogdzt9WnV9v+lJ41ouQvCNE/YM3FcZ7DIdlGPtUFosDW6wz4926tEBTsrnnC79DyoLP3eWHYvgkfUfHtCAeOcWuqr89ckm3VQ2hOIS2yBHC+UeAU4PmwQd3h6gz/bn2RBUB3OhiW+VPKeFP5Tf12IlrmbcjgHv+RRO5vx2HLum65Sic3+i8wQDmqMXhzq+2/qgqgc3pk6plS6xbrPl5imwEHA03sOh88by2JThqmBmBscT5mgO/rIQGhm6USD8QS1NK50EVEssVr3avw539QhzxnMQRRtpXWi7woeydFaZmaZYyLUJGz2R5cxLp9mxASaXedI5kiZ/Jrn2XMHiXfhyXep+ycVXCuNilk+c=
  template:
    metadata:
      name: s3-creds
      namespace: cnpg-system
    type: Opaque
