---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitea
  namespace: cnpg-system
spec:
  instances: 1
  bootstrap:
    initdb:
      owner: app
      database: gitea
      secret:
        name: gitea-db-creds
  storage:
    storageClass: nfs-ceph
    size: 10Gi
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: minio
