apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich
  namespace: cnpg-system
spec:
  instances: 1 # Ceph already has resilience in terms of storage
  primaryUpdateStrategy: unsupervised
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.5-v0.3.0

  enableSuperuserAccess: true
  superuserSecret:
    name: immich
  postgresql:
    shared_preload_libraries:
      - "vectors.so"
  storage:
    storageClass: nfs-ceph
    size: 10Gi
