apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich
  namespace: cnpg-system
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.5-v0.3.0

  enableSuperuserAccess: true
  superuserSecret:
    name: immich
  postgresql:
    shared_preload_libraries:
      - "vectors.so"
  storage:
    storageClass: nfs-ceph
    size: 10Gi
  backup:
    barmanObjectStore:
      destinationPath: "s3://cnpg-backup"
      endpointURL: "https://s4.bqc0n.com"
      s3Credentials:
        accessKeyId:
          key: ACCESS_KEY
          name: s3-creds
        secretAccessKey:
          key: SECRET_KEY
          name: s3-creds
      data:
        compression: bzip2
      wal:
        compression: bzip2
    retentionPolicy: "7d"
