---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: apps
  namespace: cnpg-system
spec:
  instances: 3
  storage:
    storageClass: nfs-ceph
    size: 10Gi
  managed:
    roles:
      - name: plane
        ensure: present
        comment: "Used by plane"
        login: true
        passwordSecret:
          name: apps-plane-db-creds
  backup:
    barmanObjectStore:
      destinationPath: "s3://cnpg-backup"
      endpointURL: "http://s4.bqc0n.com"
      s3Credentials:
        accessKeyId:
          key: ACCESS_KEY
          name: s3-creds
        secretAccessKey:
          key: SECRET_KEY
          name: s3-creds
      data:
        compression: bzip2
      wal:
        compression: bzip2
    retentionPolicy: "7d"
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: paperless-ngx
  namespace: cnpg-system
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: paperless-ngx
      owner: paperless-ngx
      secret:
        name: paperless-ngx
  storage:
    storageClass: nfs-ceph
    size: 10Gi
  backup:
    barmanObjectStore:
      destinationPath: "s3://cnpg-backup"
      endpointURL: "http://s4.bqc0n.com"
      s3Credentials:
        accessKeyId:
          key: ACCESS_KEY
          name: s3-creds
        secretAccessKey:
          key: SECRET_KEY
          name: s3-creds
      data:
        compression: bzip2
      wal:
        compression: bzip2
    retentionPolicy: "7d"
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: redmine
  namespace: cnpg-system
spec:
  instances: 2
  bootstrap:
    initdb:
      secret:
        name: redmine-db-password
  storage:
    storageClass: nfs-ceph
    size: 10Gi
  backup:
    barmanObjectStore:
      destinationPath: "s3://cnpg-backup"
      endpointURL: "http://s4.bqc0n.com"
      s3Credentials:
        accessKeyId:
          key: ACCESS_KEY
          name: s3-creds
        secretAccessKey:
          key: SECRET_KEY
          name: s3-creds
      data:
        compression: bzip2
      wal:
        compression: bzip2
    retentionPolicy: "7d"
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitea
  namespace: cnpg-system
spec:
  instances: 2
  bootstrap:
    initdb:
      owner: app
      database: gitea
      secret:
        name: gitea-db-creds
  storage:
    storageClass: nfs-ceph
    size: 10Gi
  backup:
    barmanObjectStore:
      destinationPath: "s3://cnpg-backup"
      endpointURL: "http://s4.bqc0n.com"
      s3Credentials:
        accessKeyId:
          key: ACCESS_KEY
          name: s3-creds
        secretAccessKey:
          key: SECRET_KEY
          name: s3-creds
      data:
        compression: bzip2
      wal:
        compression: bzip2
    retentionPolicy: "7d"
