apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: paperless-ngx
  namespace: cnpg-system
spec:
  instances: 1 # Ceph already has resilience in terms of storage
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: paperless-ngx
      owner: paperless-ngx
      secret:
        name: paperless-ngx
  storage:
    storageClass: nfs-ceph
    size: 10Gi
  backup:
    barmanObjectStore:
      destinationPath: "s3://cnpg-backup/paperless-ngx"
      endpointURL: "https://s4.bqc0n.com"
      s3Credentials:
        accessKeyId:
          key: ACCESS_KEY
          name: s3-creds
        secretAccessKey:
          key: SECRET_KEY
          name: s3-creds
      data:
        compression: bzip2
      wal:
        compression: bzip2
    retentionPolicy: "7d"
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: redmine
  namespace: cnpg-system
spec:
  instances: 1
  bootstrap:
    initdb:
      secret:
        name: redmine-db-password
  storage:
    storageClass: nfs-ceph
    size: 10Gi
  backup:
    barmanObjectStore:
      destinationPath: "s3://cnpg-backup/postgres"
      endpointURL: "https://s4.bqc0n.com"
      s3Credentials:
        accessKeyId:
          key: ACCESS_KEw
          name: s3-creds
        secretAccessKey:
          key: SECRET_KEY
          name: s3-creds
      data:
        compression: bzip2
      wal:
        compression: bzip2
    retentionPolicy: "7d"
