apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: paperless-ngx
  namespace: cnpg-system
spec:
  instances: 1 # Ceph already has resilience in terms of storage
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: paperless-ngx
      owner: paperless-ngx
      secret:
        name: paperless-ngx
  storage:
    storageClass: nfs-ceph
    size: 10Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: redmine
  namespace: cnpg-system
spec:
  instances: 1
  bootstrap:
    initdb:
      secret:
        name: redmine-db-password
  storage:
    storageClass: nfs-ceph
    size: 10Gi
  backup:
    barmanObjectStore:
      destinationPath: "s3://backup/postgres"
      endpointURL: "https://b10e567bb8146c35a101bec133d4a82f.r2.cloudflarestorage.com"
      s3Credentials:
        accessKeyId:
          key: ACCESS_KEY_ID
          name: r2-creds
        secretAccessKey:
          key: SECRET_KEY
          name: r2-creds
      data:
        compression: bzip2
      wal:
        compression: bzip2
    retentionPolicy: "7d"
