apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: redmine
  namespace: cnpg-system
spec:
  instances: 1
  bootstrap:
    recovery:
      source: origin
      secret:
        name: redmine-db-password
  storage:
    storageClass: nfs-ceph
    size: 10Gi
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: minio
  externalClusters:
    - name: origin
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: minio
          serverName: redmine-gen2
