---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-ngx
  namespace: cnpg-system
spec:
  encryptedData:
    password: AgCGj0qyOCHUEcMXadV2mJ6iOcimxpgbzMsDgf62dA81Xz6JDyTplYlRZnWDdOpw4Zy73PXD3LG3EulNj/K6xG+DZgGN6gRYiiOmly9rRAEuPH4svEa33APSieOunMN7ipZBoh5JgW/psSwANlZi7wn8PbyiYZU4CeOK8wZZQjXMZ5G+jV4JG/V4+2cIujd+zErfl4pvJ+gm6ppQBX7yula+BytCafVkVlxbMs4pmxm3pTNcJgzkvswxXIF41R1LWb7Z3PtAZ+qJ7BpbR0aNZ3q8FGZq4lcYr9Vzy6S/2fAMbENvCpPivGgFjRH6WsN90Q1Qw2slx+sqbVEbN2tb+GTR6L2p0Nht0OMdx9JRAYJd50wN2AmCoogUzdmNp7xrNA/Y6JvPWIGcTDJ+/pp+Pt3ppHwpYvDupP4GenP7b/LRgaW15fiPYyA/Kq5pPH2f+BJxDqeE2cjxV+5LNoGrrFM6Kst+m5d+5j8H7dXNZY/N/sQIo7ZPvA/2ml9Ajx7X7U43cpi8gZMIoy4G9tod6uejZcE8MM11Dh3Nv3lP3NkDJ2Lp3RIkT+Goff88gN/8/5VGNZfoldbYFn7QF5dh9WGfBA4KjLgM3o9VnES0uusY4O+OyPFJF97joFK0Z8VkmpK3ildAqoUDxcTIY3ZXyIEQjij63sPtZuTVxq3mwDh8k1Y9yBSMDgExf3xTCM3rX35Gx0wixr9fok3OAc7piLrEh2jUFN3k6vU5IwKKazkDRf0nmUGLh6GA33ociZStkUlMCzv5ubcDJakS71raOa8S
    username: AgDWw31vb09QEuyaifLZH2/SfkNLkauFs3VOSZt0PpfMFvHW4yezv3WO3Nyc/wISv3uaVgrRCuaRvEC8yFbyhRbfK+4Vfx0a7f+KSPAS6fHCcPkVHuhqowudagL9bJPG/3JDzkuiRN7/m3XDwVAGWmVtJnxv12SLeT129C8GDEbyK8y8o89hdxKDVxOnsuj6fqlQb3YUGgeHQJOAY5I3YMBsKTAEkTc9sK1/a+rUi6A1UFTU+qsCcBFbdG2DcGJAKfioVhvEcYYh9MPo/AFJuvWXq7UqgXsh1TJyihC32daL8XVY0rhvGl5uP9zjurvC5HFHcLorWrGHlXU2sd/aA6ZnNhdFB/4pOXhFGzK5hnI9ZGQ7xN+tmRkLECG8uOTvESf+FOF9JrgDNIGIjLSuikhPqT1KsnkskJiXwBzUQ8aHlVYPpXK19zbP+Y5i9l1q8YCyDQeZmurczdMX0gOKfpxASf0cVHOYmOjlZMe399GIAjSIbemToK7+NW+zVlqg7Ao9+N1BfCHb5wQGOQXYGX1I7ycWWFvNhmtVNWHWcZJ/iR6bfbGeKLTsAVUIco8zGCxpXpvXw1juqZvGISefbG7Cm6IlD/V8TXCjBDto6ZdqVeuaFcAKXO1RHWObXcN9a9ZmbIPO8TD90iYl7W+ItEQxVXcazIQYKRbhhaCwC06WbC2jihoHa2yajETVGbbob4L3CL906AxG/SlszEWU
  template:
    metadata:
      name: paperless-ngx
      namespace: cnpg-system
    type: kubernetes.io/basic-auth
