---
apiVersion: v1
kind: Service
metadata:
  name: homebox
  namespace: homebox
spec:
  selector:
    app: homebox
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7745
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homebox
  namespace: homebox
  labels:
      app: homebox
spec:
  selector:
    matchLabels:
      app: homebox
  template:
    metadata:
      labels:
          app: homebox
    spec:
      containers:
        - name: homebox
          image: ghcr.io/sysadminsmedia/homebox:0.18.0
          ports:
            - containerPort: 7745
          volumeMounts:
            - mountPath: /data
              name: homebox-data
      volumes:
        - name: homebox-data
          persistentVolumeClaim:
            claimName: homebox-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebox-data
  namespace: homebox
spec:
  storageClassName: nfs-ceph
  accessModes:
      - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---