---
apiVersion: v1
kind: Service
metadata:
  name: git
  namespace: web-apps
spec:
  selector:
    app: gitea
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: web-apps
  labels:
    app: gitea
spec:
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - name: gitea
          image: docker.gitea.com/gitea:1.24.2
          ports:
            - containerPort: 3000
            - containerPort: 22
          envFrom:
            - configMapRef:
                name: gitea-config
            - secretRef:
                name: gitea-secrets
          volumeMounts:
            - mountPath: /data
              name: gitea-data
      volumes:
        - name: gitea-data
          persistentVolumeClaim:
            claimName: gitea-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-data
  namespace: web-apps
spec:
  storageClassName: nfs-ceph
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-config
  namespace: web-apps
data:
  GITEA__database__DB_TYPE: postgres
  GITEA__database__HOST: gitea-rw.cnpg-system.svc.cluster.local.:5432
  GITEA__database__NAME: gitea
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-secrets
  namespace: web-apps
spec:
  encryptedData:
    GITEA__database__PASSWD: AgDfY090Y63kIOCflJ6gHcRuVNU0P3jcbw1QEywqCi/P3fmLgZ5st+jiPX3bft9Sr5559aLZaTD6mHmI8YHVeyXoYPDivHZzZM+KkzNYL02WfEw5buiVCMQT2xFXa+qBmuzE2d4I5Z2Ctp9szkC+Qp2TboCGE7A7DKey8IOzeZciEU6ePU+mBqpYd3zE7gpC/tw55aLQIzPOm3sc6aWgvpSYY3VrhKAMZTz7YyDuxkASdOouSAYw90LozdZDaznFDvXkmKYGkGcpdwIxdeTPrqRLR5UMZVvBth7DJ1tTwX3dPOPwca7FVSHPQ9TIzHYHKeztOBg5CcIzcb+u1yJE/VFKVATCg37aOhrGzupW0XDk1MO5oUBoP4UGBPk9inXKD3Yiq7o8+9jTMCfe8+1npuqWRwCOA3pQ6UR8VTRlZaohkTVXW8xGyRNXNgtu1igmpnliWCfkw0sk4wg7FnJ3XGfMBjY4pKtjMQxsKeC8k4XL5YqR9zdZDCYaCXBkmHzK5LvASc/cgXvxQp1kWZtGTP0Q6FekC1/nagBL6BQ57JY/ZdbvC6eS3gPsZ/lKIZEfnpX6Ir+ts5SzsfiOxtPMvbp1bLLnSJFtm8SFzaCRH2B0k4k4krw/ATnuKALdc7GRRE5e7Ra1gaVxlavYzwOfByLwR8DN530uV5tDT4pjarIxsmBZOgktiNH263s1gPlEJOx65VXrDNOxFLGpIFa7d1yvBLS76Pbnd5l/6g==
    GITEA__database__USER: AgCY8CjwWxFkU0P524Q7lLWeFcXsKcw9k9Pi/pGIpe36aQivNJlmK1FBCZj1ViXC6mqc3yNQch1XnLKC4jZpA/oHr9M03Ph0ltUnDBqZagGfg9B/Jy6KXfihn0VtW8iELzTiQGk5T83g9YrgVyidxgnBUu8AWDkAI5+M8O5NOW5fYkamwRDrDQpCS5lcz1RcL/DJJbwVB/J743wxI/gwl9z1HNQyE7Snei/hDEV8guNyBG2XTR+rvexPpB3oPdQmMvnMgRr3maU/aHVJXAR6ySxsl9Zbj9KKXhbqLOnXIMSA7FvTey9WH5juxymIWzKJ+toRti3403UzfTXk6EIm7cv/T2BUFF9mysh37yuEcdTkITE4iBC9NOkBSxfyoCaKnjSGB09O+r1tqgUIOrCCT58qI5hhzOIqlI0a7v4IiAqToeMIN06q86LXRkHhHmPtIuOMlBLDXnQObdeu2jx1/gc6fzdXVGkK465ZpveAiPigw0FyvnSKtsuUlBjcmAxWwFU5/oDmILEoFP+CV6VG9w6MsjaXo4O+zkcg/ir0dq6Llq5TSFFy3r+ijhbQIkeGYcqKc22jJxSz7DAJW7fJxKqVuNmoZ185rglvaYgo8IoDsZUlfLM8A73WXFeCVrfa1WcB5dq8PV+y1hiwf121maBotU58nwKu1RT6A5oKPzTAQVG5s7VNNXwyFaZudNF7adMRIFG8jw==
  template:
    metadata:
      name: gitea-secrets
      namespace: web-apps
    type: Opaque
