# TODO
#---
#apiVersion: bitnami.com/v1alpha1
#kind: SealedSecret
#metadata:
#  name: restic-repo-password
#  namespace: web-apps
#spec:
#  encryptedData:
#    PASSWORD: AgA6KcugQdxtVnV3BPwgtyqMmHXTNr7o5RCCH2io9wmlx3wbt9eDU3r0eIYlQRciTGecGDs9/ub5RBB5MSePkHhi7TgwVUpbEPPmj3pEE3gZjIRwbUnuUkKFHbfRNXqBEag1i2jVoEYoECdwt8VZWVky9/uUjoF4aOCUaCC4kgLVzE7GC9fbQgxifRcZHUAORR2DZR6slt2K7bWvQPPwMdQrmRPI0jpNtRzZuy1/rl52u8MadWcojS1hrFyohJyTNt7sZ/gKGidpHLT/Lx/C9LcPFu77fQ/OQV97teMB3w13UPEl2Y8Wy614RXNIiXnY59Y3E/A556ubwNmvlZyOH5dmEQ8oDURhmuKTfLSjPB1r18Ew1u5pifzhez5GnjsS6XU080K8jBpGr9eh3ZYfRNxwYJeTSOarcvhSDmLS0KD9CkNntnApgCp0sfdpDmmWBGLwIZKZpgAeshW5JzhsX7TM0SDRYZXCsk5QNoW8hGEVsc+okAXk4hnrcB1PRDfwuZCgmaeE8URnCrbg5iGpnjbyrP3HEjz/KszXpPFAum0d4FeBhEcn14gIB+nZfox/2aAN/B7tFi8m8NaQ4JplmsgbJKU3pqO9y2GjptpKs+tF9MI2kzHy7CCMSy1LuKcNer05aFcdFQsVHMbBOZKIVQAVMNmhCI2oovPt+DKOJ60QnmTMEfhvaQM3zQpDJ9WFrHn+hUXZVFeXBFjQOF+gFPLmqaAWqC+pITA=
#  template:
#    metadata:
#      name: restic-repo-password
#      namespace: web-apps
#    type: Opaque
#---
#apiVersion: k8up.io/v1
#kind: Schedule
#metadata:
#  name: misskey-backup-schedule
#  namespace: web-apps
#spec:
#  podSecurityContext:
#    runAsUser: 0
#  failedJobsHistoryLimit: 2
#  successfulJobsHistoryLimit: 2
#  backup:
#    schedule: "0 3 * * *" # 3AM
#    failedJobsHistoryLimit: 2
#    successfulJobsHistoryLimit: 2
#  prune:
#    schedule: "@weekly"
#    activeDeadlineSeconds: 7200
#    retention:
#      keepDaily: 14
#      keepMonthly: 12
#      keepYearly: 100
#  backend:
#    rest:
#      url: "http://restic-rest.default.svc.cluster.local./misskey/backup"
#    repoPasswordSecretRef:
#      name: restic-repo-password
#      key: PASSWORD
