---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: restic-repo-password
  namespace: web-apps
spec:
  encryptedData:
    PASSWORD: AgApBAsPWyhd4LNRHnCEISL+bPdKDHCLxU7j1b0CqO1IZ2PCothm0L/fTjddq5u14wF8lH+YGPbn98xKN7iREecmPSI7bONM5jvfT2AxgKIrw71s2O1vpSK+0gXzT2hrbySUoh5X+eZeEui21krse2djv/NeazsaP91cvY8VbigisVfDDPg6l5yqs/A5GNLdHLBPeTVkyzJ6pIE6VllWroQC+ma3m/mVWm1VagoHjZKsO9UK62d5G72XzTJeDA2slubi7hYo3oPj55rmgaRMrK0uaR8tnJokboiP0/tcl77JT/+uA/waOFQVJbXES5pa/bkgLag9wf74T+j+vCqvLSbfJ13q0r0NgZsTdPQfHkJzSIXTAv77QxQRTcagF+Ge/nwubDP+/p/NoNqiEZKZj/cqcgBwrARCfqHE37IXFPYb51KHIz26nW5MfBVIn2HPCHfi59roaTcBCca8cXVDymkQmuIu9HfAib2onx0fWo7qCKDDw888O3M+SN0x1PBiwj+NwTiQLDT8OPeR0XH7nRsfpn6UpYBzmj2hLCnjwkZRjdSBG6rEs6jt7GzvXg84Y4pr0WVs8z0KIeBSU6yu+5y4HpaBIG5Nv2XOYh4cw6JehRxiahpoVTeg8rqVKDcSjRkizTshQ+uy7eBeG6BLKtD60jnog6Ya7J/ZUqCm+ayIWahnWLJxrHs9TpG2BP7K3nQ+Jx+wnXES/kcj8+Eu0f/603lwuHAu3Zk=
  template:
    metadata:
      name: restic-repo-password
      namespace: web-apps
    type: Opaque
---
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: misskey-backup-schedule
  namespace: web-apps
spec:
  podSecurityContext:
    runAsUser: 0
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  backup:
    schedule: "0 3 * * *" # 3AM
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 2
  prune:
    schedule: "@weekly"
    activeDeadlineSeconds: 7200
    retention:
      keepDaily: 14
      keepMonthly: 12
      keepYearly: 100
  backend:
    rest:
      url: "http://restic-rest.default.svc.cluster.local./misskey/backup"
    repoPasswordSecretRef:
      name: restic-repo-password
      key: PASSWORD
