---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-misskey-files
  namespace: web-apps
spec:
  storageClassName: nfs-ceph
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: misskey
  namespace: web-apps
spec:
  selector:
    app: web
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: misskey-web
  namespace: web-apps
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "50%"
      maxSurge: "50%"
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: misskey/misskey:2025.12.2
          volumeMounts:
            - mountPath: /misskey/files
              name: misskey-files
            - mountPath: /misskey/.config
              readOnly: true
              name: misskey-config
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "2Gi"
          command: ["pnpm", "run", "migrateandstart"]
          env:
            - name: DATABASE_USER
              value: "misskey"
            - name: DATABASE_DB
              value: "misskey"
            - name: TZ
              value: Asia/Tokyo
          envFrom:
            - secretRef:
                name: misskey-db-password
      volumes:
        - name: misskey-files
          persistentVolumeClaim:
            claimName: pvc-misskey-files
        - name: misskey-config
          configMap:
            name: misskey-config