apiVersion: v1
kind: LimitRange
metadata:
  name: web-apps-resource-limits
  namespace: web-apps
spec:
  limits:
    - type: Container
      default:
        memory: 512Mi
      defaultRequest:
        memory: 256Mi
