---
apiVersion: v1
kind: Service
metadata:
  name: wallos
  namespace: web-apps
spec:
  selector:
    app: wallos
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallos
  namespace: web-apps
spec:
  selector:
    matchLabels:
      app: wallos
  template:
    metadata:
      labels:
        app: wallos
    spec:
      containers:
        - name: wallos
          image: bellamy/wallos:3.3.0
          volumeMounts:
            - mountPath: /var/www/html/db
              name: wallos-db
            - mountPath: /var/www/html/images/uploads/logos
              name: wallos-files
          env:
            - name: TZ
              value: "Asia/Tokyo"
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 256Mi
      volumes:
        - name: wallos-db
          persistentVolumeClaim:
            claimName: wallos-db
        - name: wallos-files
          persistentVolumeClaim:
            claimName: wallos-files
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallos-db
  namespace: web-apps
spec:
  storageClassName: nfs-ceph
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallos-files
  namespace: web-apps
spec:
  storageClassName: nfs-ceph
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
