---
- name: Firewalld | Open Service Ports
  become: true
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    zone: public
    state: enabled
  with_items: ["ssh", "http", "https"]
- name: Firewalld | Open Ports
  become: true
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    immediate: true
    zone: public
    state: enabled
  with_items: ["2222/tcp", "27135-27141/tcp", "12303/tcp"]
