---
- name: SELinux | Check if haproxy policy is loaded
  become: true
  ansible.builtin.shell:
    cmd: "semodule -l | grep allow_haproxy_bind"
  register: selinux_policy_loaded
  changed_when: false
  failed_when: false

- name: Create Policy for HAProxy
  when: selinux_policy_loaded.stdout == ""
  ansible.builtin.blockinfile:
    path: "~/allow_haproxy_bind.te"
    insertafter: EOF
    create: true
    block: |
      module allow_haproxy_bind 1.0;

      require {
      	type unreserved_port_t;
      	type haproxy_t;
      	class tcp_socket name_bind;
      }

      #============= haproxy_t ==============

      #!!!! This avc can be allowed using one of the these booleans:
      #     nis_enabled, haproxy_connect_any
      allow haproxy_t unreserved_port_t:tcp_socket name_bind;

- name: SELinux | Load policy
  become: true
  ansible.builtin.shell:
      cmd: >
        checkmodule -M -m -o allow_haproxy_bind.mod allow_haproxy_bind.te 
        && semodule_package -o allow_haproxy_bind.pp -m allow_haproxy_bind.mod 
        && semodule -i allow_haproxy_bind.pp
  when: selinux_policy_loaded.stdout == ""