- name: Swap | Create Swapfile
  become: true
  ansible.builtin.shell:
    cmd: >
      fallocate -l 4G /swapfile2
      && chmod 600 /swapfile2
      && mkswap /swapfile2 
      && swapon /swapfile2

- name: Swap | Edit fstab
  become: true
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "/swapfile2 none swap nw 0 0"