apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backup
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: backup
    server: https://kubernetes.default.svc
  source:
    path: argocd/backup
    repoURL: https://github.com/bqc0n/homelab.git
    targetRevision: HEAD
    directory:
      recurse: true
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8up
  namespace: argocd
spec:
  destination:
    namespace: backup
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: "https://k8up-io.github.io/k8up"
    chart: k8up
    targetRevision: "4.8.3"
    helm:
      parameters:
        - name: "k8up.timezone"
          value: "Asia/Tokyo"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
