apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dash
spec:
  destination:
    namespace: dash
    server: https://kubernetes.default.svc
  source:
    path: argocd/dash
    repoURL: https://github.com/bqc0n/homelab.git
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-operator
spec:
  destination:
    namespace: dash
    server: https://kubernetes.default.svc
  source:
    repoURL: ghcr.io/grafana/helm-charts
    targetRevision: v5.19.1
    chart: grafana-operator
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
