apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: common-apps
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: argocd/default
    repoURL: git@github.com:bqc0n/homelab.git
    targetRevision: HEAD
    directory:
      recurse: true
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - CreateNamespace=true
