apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: "4.12.0"
    chart: ingress-nginx
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingresses
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: ingresses
    server: https://kubernetes.default.svc
  source:
    path: argocd/ingress
    repoURL: git@github.com:bqc0n/homelab.git
    targetRevision: HEAD
    directory:
      recurse: true
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - CreateNamespace=true
