apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeseal
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.17.0
    chart: sealed-secrets
    helm:
      releaseName: sealed-secrets
      parameters:
        - name: "fullnameOverride"
          value: "sealed-secrets-controller"
        - name: "keyrenewperiod"
          value: "0"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
