apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: misskey
spec:
  destination:
    name: ''
    namespace: misskey
    server: https://kubernetes.default.svc
  source:
    path: argocd/misskey
    repoURL: https://github.com/bqc0n/homelab.git
    targetRevision: HEAD
    directory:
      recurse: true
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - CreateNamespace=true
