apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    repoURL: https://victoriametrics.github.io/helm-charts/
    targetRevision: 0.35.1
    chart: victoria-metrics-k8s-stack
    helm:
      valuesObject:
        fullnameOverride: victoria-metrics
        vmsingle.spec:
          storage:
            storageClassName: nfs-ssd-1
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 128Gi

  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
