apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wireguard
spec:
  destination:
    namespace: wireguard
    server: https://kubernetes.default.svc
  source:
    path: argocd/wireguard
    repoURL: https://github.com/bqc0n/homelab.git
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - CreateNamespace=true
