- name: All hosts jobs
  hosts: all
  tasks:
    - name: Wait for boot
      ansible.builtin.wait_for_connection:
    - name: apt upgrade
      become: true
      ansible.builtin.apt:
        upgrade: yes
        update_cache: true
        cache_valid_time: 3600
    - name: Timezone to JST
      become: true
      community.general.timezone:
          name: "Asia/Tokyo"
