- name: All hosts jobs
  hosts: all
  tasks:
    - name: Wait for boot
      ansible.builtin.wait_for_connection:
    - name: Set Apt cache server
      become: true
      ansible.builtin.lineinfile:
        line: 'Acquire::http::Proxy "http://{{ apt_cache_server }}:3142";'
        path: /etc/apt/apt.conf.d/01proxy
        create: true
      when: ansible_host != apt_cache_server
    - name: apt upgrade
      become: true
      ansible.builtin.apt:
        upgrade: yes
        update_cache: true
        cache_valid_time: 3600
    - name: Install unattended-upgrades
      become: true
      ansible.builtin.apt:
        name: unattended-upgrades
        state: present
    - name: Configure unattended-upgrades
      become: true
      blockinfile:
        create: true
        path: /etc/apt/apt.conf.d/52unattended-upgrades-local
        insertafter: EOF
        block: |
          Unattended-Upgrade::Origins-Pattern {
            "origin=*";
          };
    - name: Timezone to JST
      become: true
      community.general.timezone:
          name: "Asia/Tokyo"
