all:
  hosts:
    pve01:
      ansible_host: 192.168.1.10
      ansible_user: root
    file_server:
      ansible_host: 192.168.1.5
      ansible_user: root
    dnsmasq:
      ansible_host: 192.168.1.2
      ansible_user: root
    secondary_dns:
      ansible_host: 192.168.1.22
      ansible_user: root
    docker-runner:
      ansible_host: 192.168.1.3
      ansible_user: ubuntu
    nfs_server:
      # いまのところ、pve01のZFSそのまま
      ansible_host: 192.168.1.10
      ansible_user: root

kube_control_plane:
  hosts:
    k8s-master:
      ansible_host: 192.168.1.60
      ansible_user: ubuntu
kube_node:
  hosts:
    k8s-worker-01:
      ansible_host: 192.168.1.61
      ansible_user: ubuntu
    k8s-worker-02:
      ansible_host: 192.168.1.62
      ansible_user: ubuntu
    k8s-worker-03:
      ansible_host: 192.168.1.63
      ansible_user: ubuntu
etcd:
  children:
    kube_control_plane:
