all:
  vars:
    apt_cache_server: 192.168.1.5

pves:
  hosts:
    pve01:
      ansible_host: 192.168.1.10
      ansible_user: root
    pve02:
      ansible_host: 192.168.1.11
      ansible_user: root
    pve03:
      ansible_host: 192.168.1.12
      ansible_user: root

nfs_server:
  hosts:
    pve01:

ansible_managed:
  hosts:
    rpi1:
      ansible_host: 192.168.1.4
      ansible_user: bqc0n
    file_server:
      ansible_host: 192.168.1.5
      ansible_user: root

kube_control_plane:
  hosts:
    k8s-master:
      ansible_host: 192.168.1.60
      ansible_user: ubuntu
      ip: 192.168.1.60
      kube_owner: root
kube_node:
  hosts:
    k8s-worker-01:
      ansible_host: 192.168.1.61
      ansible_user: ubuntu
      ip: 192.168.1.61
      kube_owner: root
    k8s-worker-02:
      ansible_host: 192.168.1.62
      ansible_user: ubuntu
      ip: 192.168.1.62
      kube_owner: root
    k8s-worker-03:
      ansible_host: 192.168.1.63
      ansible_user: ubuntu
      ip: 192.168.1.63
      kube_owner: root

etcd:
  children:
    kube_control_plane:

kube_cluster:
  children:
    kube_control_plane:
    kube_node:

