---
- name: Localhost
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Install roles & collections
      community.general.ansible_galaxy_install:
        requirements_file: requirements.yml
        type: both
    - name: Terraform Apply
      community.general.terraform:
        project_path: ../terraform/main
        state: present
        force_init: yes

- name: DNS
  hosts:
  - dnsmasq
  - secondary_dns
  gather_facts: false
  roles:
    - role: dnsmasq
      vars:
        resolv_conf_path: /etc/resolv.conf

- name: Docker Runner
  hosts: docker-runner
  gather_facts: false
  roles:
    - role: docker-runner
  vars:
    dns_server: "192.168.1.2"
    nfs_server: "192.168.1.10"

- name: Bind mount
  hosts: pve01
  tasks:
    - name: Bind mount
      ansible.builtin.shell:
        cmd: "pct set 1001 -mp0 /shared/Shared,mp=/mnt/shared"
- name: File Server
  hosts: file_server
  gather_facts: false
  roles:
    - role: file_server