---
- name: Localhost
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Install roles & collections
      community.general.ansible_galaxy_install:
        requirements_file: requirements.yml
        type: both
    - name: Terraform Apply
      community.general.terraform:
        binary_path: ~/.nix-profile/bin/tofu
        project_path: ../terraform/main
        state: present
        force_init: yes

- name: Bind mount
  hosts: pve01
  tasks:
    - name: Bind mount
      ansible.builtin.shell:
        # todo: vmid
        cmd: "pct set 302 -mp0 /shared/Shared,mp=/mnt/shared"
- name: File Server
  hosts: file_server
  gather_facts: false
  roles:
    - role: file_server