---
- name: Localhost
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Install roles & collections
      community.general.ansible_galaxy_install:
        requirements_file: requirements.yml
        type: both
    - name: Terraform Apply
      community.general.terraform:
        binary_path: ~/.nix-profile/bin/tofu
        project_path: ../terraform/main
        state: present
        force_init: yes

- name: Update pkgs
  import_playbook: apt_upgrade.yaml

- name: Bind mount
  hosts: pve01
  tasks:
    - name: Bind mount
      ansible.builtin.shell:
        # todo: vmid
        cmd: "pct set 302 -mp0 /shared/Shared,mp=/mnt/shared"
- name: File Server
  hosts: file_server
  gather_facts: false
  roles:
    - role: file_server

- name: kubernetes worker nodes
  hosts: kube_node
  gather_facts: false
  tasks:
    - name: K8s Worker | Install nfs-common
      become: true
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        name: nfs-common
        state: latest