---
- name: Provision Resources with Terraform
  hosts: localhost
  gather_facts: false
  vars_files:
    - ./vars/main.yml
  tasks:
  - name: Terraform Apply
    community.general.terraform:
      project_path: ../terraform
      state: present
      force_init: yes
      variables:
        dnsmasq_ipv6: "{{ tf_dnsmasq_ipv6 }}"

- name: Dnsmasq
  hosts: dnsmasq
  gather_facts: false
  roles:
    - role: dnsmasq
      vars:
        resolv_conf_path: /etc/resolv.conf

- name: Docker Runner
  hosts: docker-runner
  gather_facts: false
  roles:
    - role: docker-runner