---
- name: Install roles & collections
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Install roles & collections
      community.general.ansible_galaxy_install:
        requirements_file: requirements.yml
        type: both
- name: Provision Resources with Terraform
  hosts: localhost
  gather_facts: false
  vars_files:
    - ./vars/main.yml
  tasks:
  - name: Terraform Apply
    community.general.terraform:
      project_path: ../terraform
      state: present
      force_init: yes

- name: DNS
  hosts:
  - dnsmasq
  - secondary_dns
  gather_facts: false
  roles:
    - role: dnsmasq
      vars:
        resolv_conf_path: /etc/resolv.conf

- name: Docker Runner
  hosts: docker-runner
  gather_facts: false
  roles:
    - role: docker-runner
  vars:
    dns_server: "192.168.1.2"
    nfs_server: "192.168.1.10"

- name: Bind mount
  hosts: pve
  tasks:
    - name: Bind mount
      ansible.builtin.shell:
        cmd: "pct set 1001 -mp0 /shared/Shared,mp=/Shared"
- name: File Server
  hosts: file_server
  gather_facts: false
  roles:
    - role: file_server