---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: default
spec:
  encryptedData:
    TOKEN: AgBN5GsK+8NlOFpOEUdDB2PVmu4MXeXqhRRbwkkTwUDfbwZv5IxHE0OZt++57V2/Cq3oT3BzpHXd+BIS/7IukEjvcO949FdzP7ksFHghoL7Zy7e0DWmVk22KCJJ2WEOvJCNXfsvCck/Fa0tVvpJd1GQRRhOnvKm35CW3NrAPhszIhRU0opyMdxy7eaQ6QKm9AcnPO+oDU05PuYYY8WiI6dlw8LyI6PMZOjiLVj1v4zITXb9qw7uqdgkPsjYOtyMLkxTSdbUO6ECVCSMTd4WdrqWb6L7vjSSfj6HdrbVjo7c3khMhLh0QUBU9y1RIQQ1Wv650b0GfL5S3ROwaaXnib5WyLcSHzfcVLkKa++HSrzlXRunropTXD4S9OdkM3NaJR1qMeL4yHFN7y61a13C7RH/OBhkW6K/WgDrVJaiP16czYvufN3DUwLkNv3dPANoycC6VohMag6B+E0HRrVAIy7vhxPvyO8O5c+J+Vn2W/P4VZ1p+WnR3wt4Flpcov8A4Ubv7e9mF4EExN3DHH17bF1XPYe3GUUdokzJeoCI80f9uvsZ2SVnnTee7y2ME5rftqPfD+8A47DFxD3rXxwDYb3wJdxtVhjpRL6lXs8FjWUoJBlZ4ieGvNh6q1jh5gVC+UEQOPQS+VmmeW+aMoeg6VcIgKHVxfTGxWqP6a1vpvEiDSe3rkqedIEeO4ABE6+DQJQoooS4DkuFOwOOibmgJlbqcFQl3rn9k5h+gQM9SnCLF0oW9zqzy7ooT0GnwCrSj39J7zRoNym8jnZ2wdOWHAONyUzd/vPGW+oFfEMV78AjwZ6TnC2GveY1eRQwkraEZjUgaCFpCUWTVwUzb9qwH2TXG+z+eQYyM4fkQ2xOyEAMS0aJ+1yLOuBe55WhtAt3xwpMoRhB1eqzFaQg2QM1uAkS6pUvTSlsTJkqNVAqRMrvrqGW9F5SHidlrcA==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-token
      namespace: default
