apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
data:
  haproxy.cfg: |
    global
      maxconn 4096
    defaults
      log global
      retries 3
      timeout connect 5s
      timeout client 50s
      timeout server 50s 
    frontend ceph_rgw 
      bind *:7480
      default_backend ceph_rgw
    backend ceph_rgw
      server pve01 192.168.1.10:7480 check 
      server pve02 192.168.1.11:7480 check 
      server pve03 192.168.1.12:7480 check 
