all:
  hosts:
    kube_control_plane:
      ctrl1:
        ansible_host: 192.168.1.60
        ansible_user: ubuntu
    kube_node:
      node1:
        ansible_host: 192.168.1.61
        ansible_user: ubuntu
      node2:
        ansible_host: 192.168.1.62
        ansible_user: ubuntu
    etcd:
      children:
        kube_control_plane:
          ctrl1:
            ansible_host: 192.168.1.60
            ansible_user: ubuntu
