title: bqc0n Dashboard
background:
  image: https://raw.githubusercontent.com/fexli/ArknightsResource/main/avgs/49_i22.png
  blur: sm
  opacity: 50

layout:
  Overview:
    style: row
  MachineDetailsInternal1:
    header: false
    style: row
    columns: 4
  MachineDetailsInternal2:
    header: false
    style: row
    columns: 4
