title: Homepage
background:
  image: https://raw.githubusercontent.com/fexli/ArknightsResource/main/avgs/49_i22.png
  blur: sm
  opacity: 50

layout:
  Overview:
    style: row
  Machine Details:
    style: row
    columns: 4
