---
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - "3000:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
  haproxy:
    image: haproxy:lts-alpine
    container_name: haproxy
    ports:
      - "80:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/haproxy:/usr/local/etc/haproxy
  influxdb2:
    image: influxdb:2
    container_name: influxdb2
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: bqc0n
      DOCKER_INFLUXDB_INIT_PASSWORD: test1234
      DOCKER_INFLUXDB_INIT_ORG: home
      DOCKER_INFLUXDB_INIT_BUCKET: proxmox
      DOCKER_INFLUXDB_INIT_CLI_CONFIG_NAME: proxmox
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: /run/secrets/influxdb2-admin-token
    volumes:
      - influxdb2-data:/var/lib/influxdb2
      - /etc/influxdb2:/etc/influxdb2
  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - influxdb2
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana

secrets:
  influxdb2-admin-token:
    file: ./.secrets/influxdb2-admin-token

volumes:
  influxdb2-data:
  grafana-data: