---
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - "3000:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
  haproxy:
    image: haproxy:lts-alpine
    container_name: haproxy
    ports:
      - "80:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/haproxy:/usr/local/etc/haproxy
  influxdb2:
    image: influxdb:2
    container_name: influxdb2
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: bqc0n
      DOCKER_INFLUXDB_INIT_PASSWORD: test1234
      DOCKER_INFLUXDB_INIT_ORG: home
      DOCKER_INFLUXDB_INIT_BUCKET: proxmox
      DOCKER_INFLUXDB_INIT_CLI_CONFIG_NAME: proxmox
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
    secrets:
      - influxdb2-admin-token
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - /etc/influxdb2:/etc/influxdb2
  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - influxdb2
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - /etc/grafana:/etc/grafana
  webdav:
    image: bytemark/webdav
    restart: always
    ports:
      - "3002:80"
    environment:
      AUTH_TYPE: Digest
      # Auth is already performed if a user gets here, so the weakest password is fine
      USERNAME: user
      PASSWORD: aaaa
    volumes:
      - ./mc_tob/data/plugins:/var/lib/dav/data
  mc_tob:
    image: itzg/minecraft-server:java8-graalvm-ce
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    env_file:
      - ./mc_tob/mc-tob.env
    environment:
      RCON_CMDS_STARTUP:  |-
        op bqc0n
    volumes:
      - ./mc_tob/data:/data

secrets:
  influxdb2-admin-token:
    file: ./.secrets/influxdb2-admin-token

volumes:
  influxdb-data:
    driver_opts:
      type: nfs
      o: "addr=192.168.1.10,rw,soft,nfsvers=4"
      device: ":/shared/nfs/influxdb-data"
  grafana-data: