---
- name: Create /var/lib/influxdb2
  become: yes
  ansible.builtin.file:
    path: /var/lib/influxdb2
    state: directory
    mode: 0755
- name: deploy config
  become: yes
  ansible.posix.synchronize:
    src: ./influxdb
    dest: /etc/