---
- name: Wait for boot
  ansible.builtin.wait_for_connection:
- name: Gather Facts
  ansible.builtin.setup:
- name: Tokyo Timezone
  become: yes
  ansible.builtin.timezone:
    name: Asia/Tokyo
- name: Include sops secrets
  community.sops.load_vars:
    file: "secrets.sops.yml"
    name: sops
    expressions: ignore

- name: Change DNS Server
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: "DNS="
    line: "DNS={{ dns_server }}"
  notify: restart systemd-resolved

- name: Create Docker User
  become: true
  ansible.builtin.user:
      name: docker
      uid: 1001
      state: present
      shell: /bin/bash
      create_home: true
- name: Create Directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - /mnt/nfs/influxdb
    - /mnt/nfs/minecraft
    - /mnt/nfs/restic

- name: Install NFS Client
  become: true
  ansible.builtin.apt:
    name: nfs-common
    state: latest

- name: Create NFS mount
  become: true
  ansible.posix.mount:
    path: /mnt/nfs
    fstype: nfs
    src: "{{ nfs_server }}:/shared/nfs"
    state: mounted
- name: Setup Docker
  ansible.builtin.import_tasks: setup_docker.yml

- name: Homepage Configuration
  ansible.builtin.import_tasks: homepage.yml
- name: HAProxy Configuration
  ansible.builtin.import_tasks: haproxy.yml
- name: InfluxDB Configuration
  ansible.builtin.import_tasks: influxdb.yml
- name: Grafana Configuration
  ansible.builtin.import_tasks: grafana.yml
- name: Minecraft Tower of Babel
  ansible.builtin.import_tasks: mc_tob.yml
- name: Docker Compose Up
  become: yes
  community.docker.docker_compose_v2:
    project_src: /home/ubuntu
    state: present
- name: Docker Compose Restart
  become: yes
  community.docker.docker_compose_v2:
    project_src: /home/ubuntu
    state: restarted

