---
- name: Install Docker GPG Key
  become: yes
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: a+r
- name: Add Docker Repository
  become: yes
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
- name: Apt Update
  become: yes
  ansible.builtin.apt:
    update_cache: yes
- name: Install Required Packages
  become: yes
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
    state: latest
- name: Install Docker
  become: yes
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
- name: Deploy compose
  ansible.posix.synchronize:
    src: ./compose.yml
    dest: /home/ubuntu/compose.yml
- name: Deploy secrets
  ansible.posix.synchronize:
    src: ./.secrets
    dest: /home/ubuntu/
    recursive: true
