- name: K8s Ctrl thingy
  hosts: kube_control_plane
  tasks:
    - name: Wait for boot
      ansible.builtin.wait_for_connection:
    - name: Gather Facts
      ansible.builtin.setup:
    - name: Tokyo Timezone
      become: yes
      ansible.builtin.timezone:
        name: Asia/Tokyo
    - name: Include sops secrets
      community.sops.load_vars:
        file: "./../../secrets.sops.yml"
        name: sops
        expressions: ignore

    # TODO try ArgoCD
    - name: deploy manifests
      ansible.posix.synchronize:
        src: "./manifests"
        dest: "~/"
    - name: deploy cf token
      ansible.builtin.template:
        src: cloudflare-tunnel-token.j2.yml
        dest: "~/manifests/cloudflare-tunnel-token.j2.yml"

- name: K8s worker thingy
  hosts: kube_node
  tasks:
    - name: install nfs-common
      become: true
      ansible.builtin.apt:
        name: nfs-common
        update_cache: true
        state: present