---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: misskey
#data:
#  POSTGRES_PASSWORD: "test"
#type: Opaque
stringData:
  POSTGRES_USER: "misskey"
  POSTGRES_DB: "misskey"
  POSTGRES_PASSWORD: "test"
---
apiVersion: v1
kind: Service
metadata:
  name: db-svc
  namespace: misskey
spec:
  selector:
    app: misskey-db
  ports:
    - name: http
      port: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-misskey-db
  namespace: misskey
spec:
  storageClassName: nfs-ssd-1
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: misskey-db
  namespace: misskey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: misskey-db
  template:
    metadata:
      labels:
        app: misskey-db
    spec:
      restartPolicy: Always
      containers:
        - name: psql
          image: postgres:latest
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-volume
          envFrom:
            - secretRef:
                name: postgres-secret
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
          ports:
            - containerPort: 5432
      volumes:
        - name: db-volume
          persistentVolumeClaim:
            claimName: pvc-misskey-db