---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: misskey
#data:
#  POSTGRES_PASSWORD: "test"
#type: Opaque
stringData:
  POSTGRES_USER: "misskey"
  POSTGRES_DB: "misskey"
  POSTGRES_PASSWORD: "test"
---
apiVersion: v1
kind: Service
metadata:
  name: db-svc
  namespace: misskey
spec:
  selector:
    app: misskey-db
  ports:
    - name: http
      port: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-misskey-db
  namespace: misskey
  annotations:
    k8up.io/backup: "false"
spec:
  storageClassName: nfs-ceph
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: misskey-db
  namespace: misskey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: misskey-db
  template:
    metadata:
      labels:
        app: misskey-db
      annotations:
        k8up.io/backupcommand: sh -c 'PGDATABASE="$POSTGRES_DB" PGUSER="$POSTGRES_USER" PGPASSWORD="$POSTGRES_PASSWORD" pg_dump --clean'
        k8up.io/file-extension: .sql
    spec:
      restartPolicy: Always
      containers:
        - name: psql
          image: postgres:17.4-alpine
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-volume
          envFrom:
            - secretRef:
                name: postgres-secret
          ports:
            - containerPort: 5432
      volumes:
        - name: db-volume
          persistentVolumeClaim:
            claimName: pvc-misskey-db