---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-misskey-files
  namespace: misskey
spec:
  storageClassName: nfs-ssd-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: misskey
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100
  externalTrafficPolicy: Local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: misskey
spec:
  replicas: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "50%"
      maxSurge: "50%"
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: misskey/misskey:latest
          volumeMounts:
            - mountPath: /misskey/files
              name: misskey-files
            - mountPath: /misskey/.config
              readOnly: true
              name: misskey-config
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "2"
          command: ["pnpm", "run", "migrateandstart"]
          env:
            - name: DATABASE_PASSWORD
              value: "test"
            - name: DATABASE_USER
              value: "misskey"
            - name: DATABASE_DB
              value: "misskey"
            - name: TZ
              value: Asia/Tokyo
      volumes:
        - name: misskey-files
          persistentVolumeClaim:
            claimName: pvc-misskey-files
        - name: misskey-config
          configMap:
            name: misskey-config