on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
jobs:
  approve-renovate:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Approve Renovate PR
        if: github.actor == 'renovate[bot]' && contains(github.event.pull_request.labels.*.name, 'renovate')
        run:
          gh pr review ${{ github.event.pull_request.number }} --approve
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
