---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: restic-repo-password
  namespace: minecraft
spec:
  encryptedData:
    PASSWORD: AgB2ZxAOWkFiRu3LKq1QnVpMY1PGYTa09vLtl+DeM3Ij+IGrAt2fStWpNAESqFJqqBY+JORoK1Umc3Ig0D287Z6b/hWqHTW/Rg2yj1z0to7wmq5JVMkubRDbhnA51oHIxyQhxZidn5zZAmRQERcalUFJMysQFzHCF2gIaIsQiju82+yq5P/ukrtrs304gg+d8upGzmuN99eNcDDNaiWFxr2gnt/OBMuZ+uomX4OEZKAoQomSaDym7JJgg/yWBvWsWuq62EHY4lG2keaz2mMXdDoT30H2gFV8uzOs/OAZ5ZbbXvrzGx+0pP3cYMUqrVVVpQHSAkH/ETDvc4dL1oWo/38hGnYSdQJUpsq2c7CQRL/jOTzbkj5LkXNSUQkkvVmZPknwQo3JZjsiRb89x5ka25BOWv08enu05jFn90HoBLjFvVc1CcRUOYSlv/dXsUiV9E/GXqstznKAENHldbYNjmKtgyU/deFOFptw7tJvdZ3NkBPf9cHzwbvZvCo0h3AuZtDH7q+m0LqUqQe6ItprFkYqhzPePVSz9tIbpt4KGcz7Dfi6IbArkxezrp3/NXn82IQkoLZ8i3lHdRB5imRXgFl81q3jXbxEwPk6CnaTBJmN6BBKuLFvpYCtCqWCYj/Gel1sbDWWjTGDMu/jUeC2/Lnst+pxzavoj1gXTVN/be4Qlh0s7Avift8D7PmjApGJpb/z793w8vfKcvxRbVUvse9N4JYlqojYFhwP+uOPQVN5NQ==
  template:
    metadata:
      name: restic-repo-password
      namespace: minecraft
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-backups-creds
  namespace: minecraft
spec:
  encryptedData:
    ACCESS_KEY: AgCEcIjjE9wBMY2gDWvCi5CaZYONS4gIj+QjpwRBPgGNDpYVjpVzDXalDJ2HU+ey625YDwljxoffpK7OTA4i7U6es8Iwvc4lcUF9Jd1Yb50skOZD9A+TO7OATUKV3/oF/20ZbtV6QOUmmkgU6ddf3n1x/t2WngKSGkrG5f7Hf32FTOLpYxjuBZVYPlIEOqIfeEEZiq4cL+TDiHlPG01Ol4AmSf6R8UH2WKjwNScEpbuihOQkJS+B4+2g1ghtWytUbt0cwRlpnIZNZOSEVkSTWfX76QlJfRJe+XjWrzlKsIB57+USvbnNG9AMmuB01g9wOubxP6IDSosqVVmr//3TULxfl2niN7+kAx/gcslkdxR5fERUlRlgh7bmJkqmgLrW8ueKpzMoJ4y3PC+hY+ZcecZNfzFrF7MOAT4CGTp4xoRa/4Gtmd2oJASrA28mDLasfXCG+y11BZRNSPt55qvUJPcTnrH23JmWyNwie8s8rcbeMLiQ/Em4YCHxjuCfjhFZL1rEw7nS+Sp5el8Hygk/n7l3zUXqX7j6mCxGQeQnS8brKPK1CjpRmDQDU2hU84ySBXfUfxifHnxANcc6pBnRXjCv83BN1W87fFD1LLfhIAs6K0hP6EFVh/gg5q6v2dWxellfdzCHucZ02HZRjt6gJ59WbWQ8xQTUyJ/jZ71sx0o3pDtFiYvyPWdyWDAJHuv4rb9tNWebmVCqFnMuVWgF0lrI8nx0BQ==
    SECRET_KEY: AgCTMB023vivD9txVl/tAFQZ5ZCWrj/EHMpYaH3NN8PHFugb3B/YsVqL/eDcawceslBqXGQqbXDY8Nw1puZaGaR3PQP7yxWm70gyoim16U+zXhvWSeSbkB4o4z3eNGEkFvMj2TaxhqvABC01BY/qL7U+LqKCro6UOuTSHfmRFI2UzuQuSPxNca5wOxW94Ha+J0d6hOtC+Sm02i+epoRlSVGXdNgFrdZWkTF6rt2/wxFBBGhTHQQIl8WxY9bl/CESnpF1y3O7lI5TnGLfcfLxuT5TAd47AqfhB4/PVF/IVMAVoVNYNW74rTMfxI+AVth9jcLAZ8/4iZNKszJ3hDTjlD1smyZ0zk0LSe6oxKq7hL1+Y1TI+rKK7ZoyYkHhRmmm2rCTe3CwooRLKYyoLYCToLUt505oiFrisaXTZE0PIo/oK2mr+sdZVt/SA7b8xDKRTIdvV67RlH8JB8Nyu+wCncu0IKMwjiryLA84E4fp6S3m8LOrEg8m9CzLfEQ4LuoeAEwPFRqRl2c0m1Th2CYMlK7w44BxBuiHT/WnfE+HOz+vagnN77yVRk6J/weX4LgnjdRMc9XMzM9v9W6v9VRAF9zinFDEKMrZt/nODjxKDGjIuMSzDIL55GhvyfqdOQf76EaamYEfoyntB1Y3IHJSQffPRcIq4Xk/QinMufS3o5N6e5fGpsvGoFuvKzWZ0v73W2Wn4111U8C4GKv4aHYWgiCsuP2pfIfXWLyfUXmlZa/igBpJFXM6G5is
  template:
    metadata:
      name: minio-backups-creds
      namespace: minecraft
    type: Opaque
---
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: minecraft-backup-schedule
  namespace: minecraft
spec:
  backup:
    schedule: "0 17 * * *" # Daily at 17:00 (UTC), JST 02:05
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 1
  backend:
    repoPasswordSecretRef:
      name: restic-repo-password
      key: PASSWORD
    s3:
      endpoint: https://s4.bqc0n.com
      bucket: k8s-backups/minecraft
      accessKeyIDSecretRef:
        name: minio-backups-creds
        key: ACCESS_KEY
      secretAccessKeySecretRef:
        name: minio-backups-creds
        key: SECRET_KEY
  check:
    schedule: "@weekly-random"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 1
  prune:
    schedule: "@weekly-random"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 1
    activeDeadlineSeconds: 7200
    retention:
      keepDaily: 7
      keepMonthly: 12
      keepYearly: 5
